// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/compilations/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"

	uuid "github.com/satori/go.uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCompilationsUsecase is a mock of CompilationsUsecase interface.
type MockCompilationsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCompilationsUsecaseMockRecorder
}

// MockCompilationsUsecaseMockRecorder is the mock recorder for MockCompilationsUsecase.
type MockCompilationsUsecaseMockRecorder struct {
	mock *MockCompilationsUsecase
}

// NewMockCompilationsUsecase creates a new mock instance.
func NewMockCompilationsUsecase(ctrl *gomock.Controller) *MockCompilationsUsecase {
	mock := &MockCompilationsUsecase{ctrl: ctrl}
	mock.recorder = &MockCompilationsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompilationsUsecase) EXPECT() *MockCompilationsUsecaseMockRecorder {
	return m.recorder
}

// GetCompilation mocks base method.
func (m *MockCompilationsUsecase) GetCompilation(ctx context.Context, id uuid.UUID) (models.Compilation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompilation", ctx, id)
	ret0, _ := ret[0].(models.Compilation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilation indicates an expected call of GetCompilation.
func (mr *MockCompilationsUsecaseMockRecorder) GetCompilation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilation", reflect.TypeOf((*MockCompilationsUsecase)(nil).GetCompilation), ctx, id)
}

// GetCompilations mocks base method.
func (m *MockCompilationsUsecase) GetCompilations(ctx context.Context, pager models.Pager) ([]models.Compilation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompilations", ctx, pager)
	ret0, _ := ret[0].([]models.Compilation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilations indicates an expected call of GetCompilations.
func (mr *MockCompilationsUsecaseMockRecorder) GetCompilations(ctx, pager interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilations", reflect.TypeOf((*MockCompilationsUsecase)(nil).GetCompilations), ctx, pager)
}

// GetFilmsByCompilation mocks base method.
func (m *MockCompilationsUsecase) GetFilmsByCompilation(ctx context.Context, id uuid.UUID, pager models.Pager) ([]models.FavFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByCompilation", ctx, id, pager)
	ret0, _ := ret[0].([]models.FavFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByCompilation indicates an expected call of GetFilmsByCompilation.
func (mr *MockCompilationsUsecaseMockRecorder) GetFilmsByCompilation(ctx, id, pager interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByCompilation", reflect.TypeOf((*MockCompilationsUsecase)(nil).GetFilmsByCompilation), ctx, id, pager)
}

// MockCompilationsRepo is a mock of CompilationsRepo interface.
type MockCompilationsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompilationsRepoMockRecorder
}

// MockCompilationsRepoMockRecorder is the mock recorder for MockCompilationsRepo.
type MockCompilationsRepoMockRecorder struct {
	mock *MockCompilationsRepo
}

// NewMockCompilationsRepo creates a new mock instance.
func NewMockCompilationsRepo(ctrl *gomock.Controller) *MockCompilationsRepo {
	mock := &MockCompilationsRepo{ctrl: ctrl}
	mock.recorder = &MockCompilationsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompilationsRepo) EXPECT() *MockCompilationsRepoMockRecorder {
	return m.recorder
}

// GetCompilationByID mocks base method.
func (m *MockCompilationsRepo) GetCompilationByID(ctx context.Context, id uuid.UUID) (models.Compilation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompilationByID", ctx, id)
	ret0, _ := ret[0].(models.Compilation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilationByID indicates an expected call of GetCompilationByID.
func (mr *MockCompilationsRepoMockRecorder) GetCompilationByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilationByID", reflect.TypeOf((*MockCompilationsRepo)(nil).GetCompilationByID), ctx, id)
}

// GetCompilationsWithPagination mocks base method.
func (m *MockCompilationsRepo) GetCompilationsWithPagination(ctx context.Context, limit, offset int) ([]models.Compilation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompilationsWithPagination", ctx, limit, offset)
	ret0, _ := ret[0].([]models.Compilation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilationsWithPagination indicates an expected call of GetCompilationsWithPagination.
func (mr *MockCompilationsRepoMockRecorder) GetCompilationsWithPagination(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilationsWithPagination", reflect.TypeOf((*MockCompilationsRepo)(nil).GetCompilationsWithPagination), ctx, limit, offset)
}

// GetFilmsByCompilation mocks base method.
func (m *MockCompilationsRepo) GetFilmsByCompilation(ctx context.Context, compilationID uuid.UUID, limit, offset int) ([]models.FavFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByCompilation", ctx, compilationID, limit, offset)
	ret0, _ := ret[0].([]models.FavFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByCompilation indicates an expected call of GetFilmsByCompilation.
func (mr *MockCompilationsRepoMockRecorder) GetFilmsByCompilation(ctx, compilationID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByCompilation", reflect.TypeOf((*MockCompilationsRepo)(nil).GetFilmsByCompilation), ctx, compilationID, limit, offset)
}
