// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/users/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/satori/go.uuid"
)

// MockUsersUsecase is a mock of UsersUsecase interface.
type MockUsersUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsersUsecaseMockRecorder
}

// MockUsersUsecaseMockRecorder is the mock recorder for MockUsersUsecase.
type MockUsersUsecaseMockRecorder struct {
	mock *MockUsersUsecase
}

// NewMockUsersUsecase creates a new mock instance.
func NewMockUsersUsecase(ctrl *gomock.Controller) *MockUsersUsecase {
	mock := &MockUsersUsecase{ctrl: ctrl}
	mock.recorder = &MockUsersUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersUsecase) EXPECT() *MockUsersUsecaseMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUsersUsecase) ChangePassword(ctx context.Context, id uuid.UUID, oldPassword, newPassword string) (models.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, id, oldPassword, newPassword)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUsersUsecaseMockRecorder) ChangePassword(ctx, id, oldPassword, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUsersUsecase)(nil).ChangePassword), ctx, id, oldPassword, newPassword)
}

// ChangeUserAvatar mocks base method.
func (m *MockUsersUsecase) ChangeUserAvatar(ctx context.Context, userID uuid.UUID, fileBytes []byte) (models.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserAvatar", ctx, userID, fileBytes)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ChangeUserAvatar indicates an expected call of ChangeUserAvatar.
func (mr *MockUsersUsecaseMockRecorder) ChangeUserAvatar(ctx, userID, fileBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserAvatar", reflect.TypeOf((*MockUsersUsecase)(nil).ChangeUserAvatar), ctx, userID, fileBytes)
}

// GenerateToken mocks base method.
func (m *MockUsersUsecase) GenerateToken(id uuid.UUID, login string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", id, login)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockUsersUsecaseMockRecorder) GenerateToken(id, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockUsersUsecase)(nil).GenerateToken), id, login)
}

// GetUser mocks base method.
func (m *MockUsersUsecase) GetUser(ctx context.Context, id uuid.UUID) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUsersUsecaseMockRecorder) GetUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUsersUsecase)(nil).GetUser), ctx, id)
}

// ParseToken mocks base method.
func (m *MockUsersUsecase) ParseToken(token string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", token)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockUsersUsecaseMockRecorder) ParseToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockUsersUsecase)(nil).ParseToken), token)
}

// ValidateAndGetUser mocks base method.
func (m *MockUsersUsecase) ValidateAndGetUser(ctx context.Context, token string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndGetUser", ctx, token)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndGetUser indicates an expected call of ValidateAndGetUser.
func (mr *MockUsersUsecaseMockRecorder) ValidateAndGetUser(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndGetUser", reflect.TypeOf((*MockUsersUsecase)(nil).ValidateAndGetUser), ctx, token)
}

// MockUsersRepo is a mock of UsersRepo interface.
type MockUsersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepoMockRecorder
}

// MockUsersRepoMockRecorder is the mock recorder for MockUsersRepo.
type MockUsersRepoMockRecorder struct {
	mock *MockUsersRepo
}

// NewMockUsersRepo creates a new mock instance.
func NewMockUsersRepo(ctrl *gomock.Controller) *MockUsersRepo {
	mock := &MockUsersRepo{ctrl: ctrl}
	mock.recorder = &MockUsersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepo) EXPECT() *MockUsersRepoMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockUsersRepo) GetUserByID(ctx context.Context, id uuid.UUID) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUsersRepoMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUsersRepo)(nil).GetUserByID), ctx, id)
}

// GetUserByLogin mocks base method.
func (m *MockUsersRepo) GetUserByLogin(ctx context.Context, login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockUsersRepoMockRecorder) GetUserByLogin(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUsersRepo)(nil).GetUserByLogin), ctx, login)
}

// UpdateUserAvatar mocks base method.
func (m *MockUsersRepo) UpdateUserAvatar(ctx context.Context, version int, userID uuid.UUID, avatarPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAvatar", ctx, version, userID, avatarPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAvatar indicates an expected call of UpdateUserAvatar.
func (mr *MockUsersRepoMockRecorder) UpdateUserAvatar(ctx, version, userID, avatarPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAvatar", reflect.TypeOf((*MockUsersRepo)(nil).UpdateUserAvatar), ctx, version, userID, avatarPath)
}

// UpdateUserPassword mocks base method.
func (m *MockUsersRepo) UpdateUserPassword(ctx context.Context, version int, userID uuid.UUID, passwordHash []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, version, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockUsersRepoMockRecorder) UpdateUserPassword(ctx, version, userID, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockUsersRepo)(nil).UpdateUserPassword), ctx, version, userID, passwordHash)
}
