package repo

import (
	"kinopoisk/internal/models"
	"time"

	uuid "github.com/satori/go.uuid"
)

var Actors []models.Actor

func InitActors() {
	Actors = []models.Actor{
		// 1+1 - Франсуа Клюзе
		{
			ID:            uuid.FromStringOrNil("f47ac10b-58cc-0372-8567-0e02b2c3d479"),
			RussianName:   "Франсуа Клюзе",
			OriginalName:  "François Cluzet",
			Photo:         "/static/actors/cluzet.jpg",
			Height:        178,
			BirthDate:     time.Date(1955, 9, 21, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Дева",
			BirthPlace:    "Париж, Франция",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Интерстеллар - Мэттью Макконахи
		{
			ID:            uuid.FromStringOrNil("6ba7b810-9dad-11d1-80b4-00c04fd430c8"),
			RussianName:   "Мэттью Макконахи",
			OriginalName:  "Matthew McConaughey",
			Photo:         "/static/actors/mcconaughey.jpg",
			Height:        182,
			BirthDate:     time.Date(1969, 11, 4, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Скорпион",
			BirthPlace:    "Увалде, Техас, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Побег из Шоушенка - Тим Роббинс
		{
			ID:            uuid.FromStringOrNil("550e8400-e29b-41d4-a716-446655440000"),
			RussianName:   "Тим Роббинс",
			OriginalName:  "Tim Robbins",
			Photo:         "/static/actors/robbins.jpg",
			Height:        196,
			BirthDate:     time.Date(1958, 10, 16, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Весы",
			BirthPlace:    "Уэст-Ковина, Калифорния, США",
			MaritalStatus: "В отношениях",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Джентльмены - Чарли Ханнэм
		{
			ID:            uuid.FromStringOrNil("67e55044-10b1-426f-9247-bb680e5fe0c8"),
			RussianName:   "Чарли Ханнэм",
			OriginalName:  "Charlie Hunnam",
			Photo:         "/static/actors/hunnam.jpg",
			Height:        185,
			BirthDate:     time.Date(1980, 4, 10, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Овен",
			BirthPlace:    "Ньюкасл-апон-Тайн, Англия",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Зеленая миля - Майкл Кларк Дункан
		{
			ID:            uuid.FromStringOrNil("c9bf9e57-1685-4c89-bafb-ff5af830be8a"),
			RussianName:   "Майкл Кларк Дункан",
			OriginalName:  "Michael Clarke Duncan",
			Photo:         "/static/actors/duncan.jpg",
			Height:        196,
			BirthDate:     time.Date(1957, 12, 10, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(2012, 9, 3, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Стрелец",
			BirthPlace:    "Чикаго, Иллинойс, США",
			MaritalStatus: "Не был женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Остров проклятых - Леонардо ДиКаприо
		{
			ID:            uuid.FromStringOrNil("a3bb189e-8bf9-3888-9912-6c2d5c7c5b9a"),
			RussianName:   "Леонардо ДиКаприо",
			OriginalName:  "Leonardo DiCaprio",
			Photo:         "/static/actors/dicaprio.jpg",
			Height:        183,
			BirthDate:     time.Date(1974, 11, 11, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Скорпион",
			BirthPlace:    "Лос-Анджелес, Калифорния, США",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Властелин колец: Возвращение короля - Вигго Мортенсен
		{
			ID:            uuid.FromStringOrNil("1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed"),
			RussianName:   "Вигго Мортенсен",
			OriginalName:  "Viggo Mortensen",
			Photo:         "/static/actors/mortensen.jpg",
			Height:        180,
			BirthDate:     time.Date(1958, 10, 20, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Весы",
			BirthPlace:    "Уотертаун, Нью-Йорк, США",
			MaritalStatus: "В отношениях",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Форрест Гамп - Том Хэнкс
		{
			ID:            uuid.FromStringOrNil("9f4e7a7c-8c5a-4e5a-9f3e-6e8a9b9c8d7e"),
			RussianName:   "Том Хэнкс",
			OriginalName:  "Tom Hanks",
			Photo:         "/static/actors/hanks2.jpg",
			Height:        183,
			BirthDate:     time.Date(1956, 7, 9, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Рак",
			BirthPlace:    "Конкорд, Калифорния, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Терминатор 2 - Арнольд Шварценеггер
		{
			ID:            uuid.FromStringOrNil("3f7a5c2e-1e4a-4c8e-9e2a-7b8c9d0e1f2a"),
			RussianName:   "Арнольд Шварценеггер",
			OriginalName:  "Arnold Schwarzenegger",
			Photo:         "/static/actors/schwarzenegger.jpg",
			Height:        188,
			BirthDate:     time.Date(1947, 7, 30, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Лев",
			BirthPlace:    "Таль, Австрия",
			MaritalStatus: "Разведен",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Зеленая книга - Махершала Али
		{
			ID:            uuid.FromStringOrNil("8e7c5a2b-4e1a-9c8e-2a7b-1c8d9e0f2a3b"),
			RussianName:   "Махершала Али",
			OriginalName:  "Mahershala Ali",
			Photo:         "/static/actors/ali.jpg",
			Height:        188,
			BirthDate:     time.Date(1974, 2, 16, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Водолей",
			BirthPlace:    "Окленд, Калифорния, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Властелин колец: Братство кольца - Элайджа Вуд
		{
			ID:            uuid.FromStringOrNil("5d4c3b2a-1e9f-8c7e-6a5b-4c3d2e1f0a9b"),
			RussianName:   "Элайджа Вуд",
			OriginalName:  "Elijah Wood",
			Photo:         "/static/actors/wood.jpg",
			Height:        168,
			BirthDate:     time.Date(1981, 1, 28, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Водолей",
			BirthPlace:    "Сидар-Рапидс, Айова, США",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Унесённые призраками - Руми Хиираги (озвучка)
		{
			ID:            uuid.FromStringOrNil("2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"),
			RussianName:   "Руми Хиираги",
			OriginalName:  "Rumi Hiiragi",
			Photo:         "/static/actors/hiiragi.jpg",
			Height:        158,
			BirthDate:     time.Date(1987, 8, 1, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Лев",
			BirthPlace:    "Токио, Япония",
			MaritalStatus: "Замужем",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Бойцовский клуб - Брэд Питт
		{
			ID:            uuid.FromStringOrNil("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d"),
			RussianName:   "Брэд Питт",
			OriginalName:  "Brad Pitt",
			Photo:         "/static/actors/pitt.jpg",
			Height:        180,
			BirthDate:     time.Date(1963, 12, 18, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Стрелец",
			BirthPlace:    "Шауни, Оклахома, США",
			MaritalStatus: "Разведен",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Гладиатор - Рассел Кроу
		{
			ID:            uuid.FromStringOrNil("4d5c6b7a-8e9f-0a1b-2c3d-4e5f6a7b8c9d"),
			RussianName:   "Рассел Кроу",
			OriginalName:  "Russell Crowe",
			Photo:         "/static/actors/crowe.jpg",
			Height:        182,
			BirthDate:     time.Date(1964, 4, 7, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Овен",
			BirthPlace:    "Веллингтон, Новая Зеландия",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Начало - Джозеф Гордон-Левитт
		{
			ID:            uuid.FromStringOrNil("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
			RussianName:   "Джозеф Гордон-Левитт",
			OriginalName:  "Joseph Gordon-Levitt",
			Photo:         "/static/actors/gordon-levitt.jpg",
			Height:        176,
			BirthDate:     time.Date(1981, 2, 17, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Водолей",
			BirthPlace:    "Лос-Анджелес, Калифорния, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Криминальное чтиво - Джон Траволта
		{
			ID:            uuid.FromStringOrNil("7e6d5c4b-3a2b-1c0d-9e8f-7a6b5c4d3e2f"),
			RussianName:   "Джон Траволта",
			OriginalName:  "John Travolta",
			Photo:         "/static/actors/travolta.jpg",
			Height:        188,
			BirthDate:     time.Date(1954, 2, 18, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Водолей",
			BirthPlace:    "Энглвуд, Нью-Джерси, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Унесённые ветром - Кларк Гейбл
		{
			ID:            uuid.FromStringOrNil("3e4d5c6b-7a8b-9c0d-1e2f-3a4b5c6d7e8f"),
			RussianName:   "Кларк Гейбл",
			OriginalName:  "Clark Gable",
			Photo:         "/static/actors/gable.jpg",
			Height:        185,
			BirthDate:     time.Date(1901, 2, 1, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(1960, 11, 16, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Водолей",
			BirthPlace:    "Кэдис, Огайо, США",
			MaritalStatus: "Был женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Властелин колец: Две крепости - Шон Эстин
		{
			ID:            uuid.FromStringOrNil("8f7e6d5c-4b3a-2b1c-0d9e-8f7a6b5c4d3e"),
			RussianName:   "Шон Эстин",
			OriginalName:  "Sean Astin",
			Photo:         "/static/actors/astin.jpg",
			Height:        168,
			BirthDate:     time.Date(1971, 2, 25, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Рыбы",
			BirthPlace:    "Санта-Моника, Калифорния, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Достучаться до небес - Тиль Швайгер
		{
			ID:            uuid.FromStringOrNil("5f4e3d2c-1b0a-9e8d-7c6b-5a4b3c2d1e0f"),
			RussianName:   "Тиль Швайгер",
			OriginalName:  "Til Schweiger",
			Photo:         "/static/actors/schweiger.jpg",
			Height:        182,
			BirthDate:     time.Date(1963, 12, 19, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Стрелец",
			BirthPlace:    "Фрайбург, ФРГ",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Леон - Жан Рено
		{
			ID:            uuid.FromStringOrNil("2d3e4f5a-6b7c-8d9e-0f1a-2b3c4d5e6f7a"),
			RussianName:   "Жан Рено",
			OriginalName:  "Jean Reno",
			Photo:         "/static/actors/reno.jpg",
			Height:        188,
			BirthDate:     time.Date(1948, 7, 30, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Лев",
			BirthPlace:    "Касабланка, Марокко",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Операция «Ы» - Александр Демьяненко
		{
			ID:            uuid.FromStringOrNil("9e8d7c6b-5a4b-3c2d-1e0f-9a8b7c6d5e4f"),
			RussianName:   "Александр Демьяненко",
			OriginalName:  "",
			Photo:         "/static/actors/demyanenko.jpg",
			Height:        178,
			BirthDate:     time.Date(1937, 5, 30, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(1999, 8, 22, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Близнецы",
			BirthPlace:    "Свердловск, СССР",
			MaritalStatus: "Был женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Список Шиндлера - Лиам Нисон
		{
			ID:            uuid.FromStringOrNil("4c5d6e7f-8a9b-0c1d-2e3f-4a5b6c7d8e9f"),
			RussianName:   "Лиам Нисон",
			OriginalName:  "Liam Neeson",
			Photo:         "/static/actors/neeson.jpg",
			Height:        193,
			BirthDate:     time.Date(1952, 6, 7, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Близнецы",
			BirthPlace:    "Баллимина, Северная Ирландия",
			MaritalStatus: "Вдовец",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Девчата - Надежда Румянцева
		{
			ID:            uuid.FromStringOrNil("1d2e3f4a-5b6c-7d8e-9f0a-1b2c3d4e5f6a"),
			RussianName:   "Надежда Румянцева",
			OriginalName:  "",
			Photo:         "/static/actors/rumyantseva.jpg",
			Height:        162,
			BirthDate:     time.Date(1930, 9, 9, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(2008, 4, 8, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Дева",
			BirthPlace:    "Поти, СССР",
			MaritalStatus: "Была замужем",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Темный рыцарь - Кристиан Бейл
		{
			ID:            uuid.FromStringOrNil("6e7f8a9b-0c1d-2e3f-4a5b-6c7d8e9f0a1b"),
			RussianName:   "Кристиан Бейл",
			OriginalName:  "Christian Bale",
			Photo:         "/static/actors/bale.jpg",
			Height:        183,
			BirthDate:     time.Date(1974, 1, 30, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Водолей",
			BirthPlace:    "Хаверфордуэст, Уэльс",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Тайна Коко - Энтони Гонсалес (озвучка)
		{
			ID:            uuid.FromStringOrNil("3f4a5b6c-7d8e-9f0a-1b2c-3d4e5f6a7b8c"),
			RussianName:   "Энтони Гонсалес",
			OriginalName:  "Anthony Gonzalez",
			Photo:         "/static/actors/gonzalez.jpg",
			Height:        155,
			BirthDate:     time.Date(2004, 9, 23, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Весы",
			BirthPlace:    "Лос-Анджелес, Калифорния, США",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Бриллиантовая рука - Юрий Никулин
		{
			ID:            uuid.FromStringOrNil("8a9b0c1d-2e3f-4a5b-6c7d-8e9f0a1b2c3d"),
			RussianName:   "Юрий Никулин",
			OriginalName:  "",
			Photo:         "/static/actors/nikulin.jpg",
			Height:        176,
			BirthDate:     time.Date(1921, 12, 18, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(1997, 8, 21, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Стрелец",
			BirthPlace:    "Демидов, СССР",
			MaritalStatus: "Был женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Брат - Сергей Бодров
		{
			ID:            uuid.FromStringOrNil("5b6c7d8e-9f0a-1b2c-3d4e-5f6a7b8c9d0e"),
			RussianName:   "Сергей Бодров",
			OriginalName:  "",
			Photo:         "/static/actors/bodrov.jpg",
			Height:        178,
			BirthDate:     time.Date(1971, 12, 27, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(2002, 9, 20, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Козерог",
			BirthPlace:    "Москва, СССР",
			MaritalStatus: "Был женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Брат 2 - Виктор Сухоруков
		{
			ID:            uuid.FromStringOrNil("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
			RussianName:   "Виктор Сухоруков",
			OriginalName:  "",
			Photo:         "/static/actors/sukhorukov.jpg",
			Height:        169,
			BirthDate:     time.Date(1951, 11, 10, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Скорпион",
			BirthPlace:    "Орехово-Зуево, СССР",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Собачье сердце - Евгений Евстигнеев
		{
			ID:            uuid.FromStringOrNil("9d0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a"),
			RussianName:   "Евгений Евстигнеев",
			OriginalName:  "",
			Photo:         "/static/actors/evstigneev.jpg",
			Height:        178,
			BirthDate:     time.Date(1926, 10, 9, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(1992, 3, 4, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Весы",
			BirthPlace:    "Нижний Новгород, СССР",
			MaritalStatus: "Был женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Пятый элемент - Брюс Уиллис
		{
			ID:            uuid.FromStringOrNil("4e5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b"),
			RussianName:   "Брюс Уиллис",
			OriginalName:  "Bruce Willis",
			Photo:         "/static/actors/willis.jpg",
			Height:        183,
			BirthDate:     time.Date(1955, 3, 19, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Рыбы",
			BirthPlace:    "Айдар-Оберштайн, ФРГ",
			MaritalStatus: "Разведен",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Крестный отец - Марлон Брандо
		{
			ID:            uuid.FromStringOrNil("1f2a3b4c-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
			RussianName:   "Марлон Брандо",
			OriginalName:  "Marlon Brando",
			Photo:         "/static/actors/brando.jpg",
			Height:        175,
			BirthDate:     time.Date(1924, 4, 3, 0, 0, 0, 0, time.UTC),
			DeathDate:     time.Date(2004, 7, 1, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Овен",
			BirthPlace:    "Омаха, Небраска, США",
			MaritalStatus: "Был женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Дангал - Аамир Хан
		{
			ID:            uuid.FromStringOrNil("6a7b8c9d-0e1f-2a3b-4c5d-6e7f8a9b0c1d"),
			RussianName:   "Аамир Хан",
			OriginalName:  "Aamir Khan",
			Photo:         "/static/actors/khan.jpg",
			Height:        165,
			BirthDate:     time.Date(1965, 3, 14, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Рыбы",
			BirthPlace:    "Мумбаи, Индия",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Большой куш - Джейсон Стэйтем
		{
			ID:            uuid.FromStringOrNil("3b4c5d6e-7f8a-9b0c-1d2e-3f4a5b6c7d8e"),
			RussianName:   "Джейсон Стэйтем",
			OriginalName:  "Jason Statham",
			Photo:         "/static/actors/statham.jpg",
			Height:        178,
			BirthDate:     time.Date(1967, 7, 26, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Лев",
			BirthPlace:    "Шордитч, Лондон, Англия",
			MaritalStatus: "В отношениях",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Шрэк - Майк Майерс (озвучка)
		{
			ID:            uuid.FromStringOrNil("8c9d0e1f-2a3b-4c5d-6e7f-8a9b0c1d2e3f"),
			RussianName:   "Майк Майерс",
			OriginalName:  "Mike Myers",
			Photo:         "/static/actors/myers.jpg",
			Height:        175,
			BirthDate:     time.Date(1963, 5, 25, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Близнецы",
			BirthPlace:    "Скарборо, Онтарио, Канада",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Назад в будущее - Майкл Джей Фокс
		{
			ID:            uuid.FromStringOrNil("5d6e7f8a-9b0c-1d2e-3f4a-5b6c7d8e9f0a"),
			RussianName:   "Майкл Джей Фокс",
			OriginalName:  "Michael J. Fox",
			Photo:         "/static/actors/fox.jpg",
			Height:        163,
			BirthDate:     time.Date(1961, 6, 9, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Близнецы",
			BirthPlace:    "Эдмонтон, Канада",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Дикий робот - Лупита Нионго (озвучка)
		{
			ID:            uuid.FromStringOrNil("2e3f4a5b-6c7d-8e9f-0a1b-2c3d4e5f6a7b"),
			RussianName:   "Лупита Нионго",
			OriginalName:  "Lupita Nyong'o",
			Photo:         "/static/actors/nyongo.jpg",
			Height:        165,
			BirthDate:     time.Date(1983, 3, 1, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Рыбы",
			BirthPlace:    "Мехико, Мексика",
			MaritalStatus: "Не замужем",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Поймай меня, если сможешь - Кристофер Уокен
		{
			ID:            uuid.FromStringOrNil("9f0a1b2c-3d4e-5f6a-7b8c-9d0e1f2a3b4c"),
			RussianName:   "Кристофер Уокен",
			OriginalName:  "Christopher Walken",
			Photo:         "/static/actors/walken.jpg",
			Height:        183,
			BirthDate:     time.Date(1943, 3, 31, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Овен",
			BirthPlace:    "Нью-Йорк, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Карты, деньги, два ствола - Джейсон Флеминг
		{
			ID:            uuid.FromStringOrNil("4a5b6c7d-8e9f-0a1b-2c3d-4e5f6a7b8c9d"),
			RussianName:   "Джейсон Флеминг",
			OriginalName:  "Jason Flemyng",
			Photo:         "/static/actors/flemyng.jpg",
			Height:        178,
			BirthDate:     time.Date(1966, 9, 25, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Весы",
			BirthPlace:    "Лондон, Англия",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Хатико - Ричард Гир
		{
			ID:            uuid.FromStringOrNil("1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
			RussianName:   "Ричард Гир",
			OriginalName:  "Richard Gere",
			Photo:         "/static/actors/gere.jpg",
			Height:        178,
			BirthDate:     time.Date(1949, 8, 31, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Дева",
			BirthPlace:    "Филадельфия, Пенсильвания, США",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Кавказская пленница - Наталья Варлей
		{
			ID:            uuid.FromStringOrNil("6c7d8e9f-0a1b-2c3d-4e5f-6a7b8c9d0e1f"),
			RussianName:   "Наталья Варлей",
			OriginalName:  "",
			Photo:         "/static/actors/varley.jpg",
			Height:        150,
			BirthDate:     time.Date(1947, 6, 22, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Рак",
			BirthPlace:    "Констанца, Румыния",
			MaritalStatus: "Разведена",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Трасса 60 - Джеймс Марсден
		{
			ID:            uuid.FromStringOrNil("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
			RussianName:   "Джеймс Марсден",
			OriginalName:  "James Marsden",
			Photo:         "/static/actors/marsden.jpg",
			Height:        184,
			BirthDate:     time.Date(1973, 9, 18, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Дева",
			BirthPlace:    "Стиллуотер, Оклахома, США",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Титаник - Кейт Уинслет
		{
			ID:            uuid.FromStringOrNil("8e9f0a1b-2c3d-4e5f-6a7b-8c9d0e1f2a3b"),
			RussianName:   "Кейт Уинслет",
			OriginalName:  "Kate Winslet",
			Photo:         "/static/actors/winslet.jpg",
			Height:        169,
			BirthDate:     time.Date(1975, 10, 5, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Весы",
			BirthPlace:    "Рединг, Беркшир, Англия, Великобритания",
			MaritalStatus: "Замужем",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Матрица - Киану Ривз
		{
			ID:            uuid.FromStringOrNil("5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b"),
			RussianName:   "Киану Ривз",
			OriginalName:  "Keanu Reeves",
			Photo:         "/static/actors/reeves.jpg",
			Height:        186,
			BirthDate:     time.Date(1964, 9, 2, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Дева",
			BirthPlace:    "Бейрут, Ливан",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Гарри Поттер - Дэниел Рэдклифф
		{
			ID:            uuid.FromStringOrNil("2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c"),
			RussianName:   "Дэниел Рэдклифф",
			OriginalName:  "Daniel Radcliffe",
			Photo:         "/static/actors/radcliffe.jpg",
			Height:        165,
			BirthDate:     time.Date(1989, 7, 23, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Лев",
			BirthPlace:    "Лондон, Англия",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// В августе 44-го - Евгений Миронов
		{
			ID:            uuid.FromStringOrNil("9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d"),
			RussianName:   "Евгений Миронов",
			OriginalName:  "",
			Photo:         "/static/actors/mironov.jpg",
			Height:        178,
			BirthDate:     time.Date(1966, 11, 29, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Стрелец",
			BirthPlace:    "Саратов, СССР",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// ...А зори здесь тихие - Андрей Мартынов
		{
			ID:            uuid.FromStringOrNil("4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e"),
			RussianName:   "Андрей Мартынов",
			OriginalName:  "",
			Photo:         "/static/actors/martynov.jpg",
			Height:        178,
			BirthDate:     time.Date(1945, 10, 24, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Скорпион",
			BirthPlace:    "Москва, СССР",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Пианист - Эдриан Броуди
		{
			ID:            uuid.FromStringOrNil("1c2d3e4f-5a6b-7c8d-9e0f-1a2b3c4d5e6f"),
			RussianName:   "Эдриан Броуди",
			OriginalName:  "Adrien Brody",
			Photo:         "/static/actors/brody.jpg",
			Height:        186,
			BirthDate:     time.Date(1973, 4, 14, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Овен",
			BirthPlace:    "Нью-Йорк, США",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Иди и смотри - Алексей Кравченко
		{
			ID:            uuid.FromStringOrNil("6d7e8f9a-0b1c-2d3e-4f5a-6b7c8d9e0f1a"),
			RussianName:   "Алексей Кравченко",
			OriginalName:  "",
			Photo:         "/static/actors/kravchenko.jpg",
			Height:        178,
			BirthDate:     time.Date(1969, 10, 10, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Весы",
			BirthPlace:    "Москва, СССР",
			MaritalStatus: "Женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Джанго освобожденный - Джейми Фокс
		{
			ID:            uuid.FromStringOrNil("3e4f5a6b-7c8d-9e0f-1a2b-3c4d5e6f7a8b"),
			RussianName:   "Джейми Фокс",
			OriginalName:  "Jamie Foxx",
			Photo:         "/static/actors/foxx.jpg",
			Height:        175,
			BirthDate:     time.Date(1967, 12, 13, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Стрелец",
			BirthPlace:    "Террелл, Техас, США",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		// Дюна: Часть вторая - Тимоти Шаламе
		{
			ID:            uuid.FromStringOrNil("8f9a0b1c-2d3e-4f5a-6b7c-8d9e0f1a2b3c"),
			RussianName:   "Тимоти Шаламе",
			OriginalName:  "Timothée Chalamet",
			Photo:         "/static/actors/chalamet.jpg",
			Height:        178,
			BirthDate:     time.Date(1995, 12, 27, 0, 0, 0, 0, time.UTC),
			ZodiacSign:    "Козерог",
			BirthPlace:    "Нью-Йорк, США",
			MaritalStatus: "Не женат",
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
	}
}
