package repo

import (
	"kinopoisk/internal/models"
	"time"

	uuid "github.com/satori/go.uuid"
)

var Films []models.Film

func InitRepo() {
	InitGenres()
	InitFilms()
	InitUsers()
}

func InitFilms() {
	Films = []models.Film{
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "1+1",
			Genres:      []models.Genre{Genres[7]},
			Year:        2011,
			Country:     "Франция",
			Rating:      8.3,
			Budget:      43507244,
			Fees:        79676250,
			PremierDate: time.Date(2011, 04, 07, 0, 0, 0, 0, time.UTC),
			Duration:    112,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic1.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Интерстеллар",
			Genres:      []models.Genre{Genres[22]},
			Year:        2014,
			Country:     "США",
			Rating:      8.3,
			Budget:      38478055,
			Fees:        72437114,
			PremierDate: time.Date(2014, 01, 24, 0, 0, 0, 0, time.UTC),
			Duration:    149,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic2.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Побег из Шоушенка",
			Genres:      []models.Genre{Genres[7]},
			Year:        1994,
			Country:     "США",
			Rating:      8.2,
			Budget:      34495536,
			Fees:        122193072,
			PremierDate: time.Date(1994, 01, 15, 0, 0, 0, 0, time.UTC),
			Duration:    142,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic3.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Джентльмены",
			Genres:      []models.Genre{Genres[11]},
			Year:        2019,
			Country:     "США",
			Rating:      8.2,
			Budget:      33735515,
			Fees:        98773593,
			PremierDate: time.Date(2018, 12, 01, 0, 0, 0, 0, time.UTC),
			Duration:    113,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic4.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Зеленая миля",
			Genres:      []models.Genre{Genres[7]},
			Year:        1993,
			Country:     "США",
			Rating:      8.2,
			Budget:      15227519,
			Fees:        61379410,
			PremierDate: time.Date(1993, 03, 26, 0, 0, 0, 0, time.UTC),
			Duration:    189,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic5.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Остров проклятых",
			Genres:      []models.Genre{Genres[20]},
			Year:        2009,
			Country:     "США",
			Rating:      8.1,
			Budget:      39542037,
			Fees:        66861053,
			PremierDate: time.Date(2009, 07, 22, 0, 0, 0, 0, time.UTC),
			Duration:    138,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic6.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Властелин колец: Возвращение короля",
			Genres:      []models.Genre{Genres[23]},
			Year:        2003,
			Country:     "Новая Зеландия",
			Rating:      8.1,
			Budget:      7181479,
			Fees:        99769757,
			PremierDate: time.Date(2003, 05, 15, 0, 0, 0, 0, time.UTC),
			Duration:    201,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic7.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Форрест Гамп",
			Genres:      []models.Genre{Genres[7]},
			Year:        1994,
			Country:     "США",
			Rating:      8.0,
			Budget:      42217931,
			Fees:        125303883,
			PremierDate: time.Date(1994, 02, 25, 0, 0, 0, 0, time.UTC),
			Duration:    142,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic8.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Терминатор 2: Судный день",
			Genres:      []models.Genre{Genres[22], Genres[18]},
			Year:        1991,
			Country:     "США",
			Rating:      8.0,
			Budget:      7064498,
			Fees:        68148168,
			PremierDate: time.Date(1991, 12, 28, 0, 0, 0, 0, time.UTC),
			Duration:    137,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic9.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Зеленая книга",
			Genres:      []models.Genre{Genres[1]},
			Year:        2018,
			Country:     "США",
			Rating:      8.0,
			Budget:      26493559,
			Fees:        81491402,
			PremierDate: time.Date(2018, 11, 04, 0, 0, 0, 0, time.UTC),
			Duration:    130,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic10.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Властелин колец: Братство кольца",
			Genres:      []models.Genre{Genres[22]},
			Year:        2001,
			Country:     "Новая Зеландия",
			Rating:      8.0,
			Budget:      21304461,
			Fees:        120089460,
			PremierDate: time.Date(2001, 01, 16, 0, 0, 0, 0, time.UTC),
			Duration:    178,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic11.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Унесённые призраками",
			Genres:      []models.Genre{Genres[0]},
			Year:        2001,
			Country:     "Япония",
			Rating:      8.0,
			Budget:      45614172,
			Fees:        105636789,
			PremierDate: time.Date(2001, 12, 15, 0, 0, 0, 0, time.UTC),
			Duration:    124,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic12.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Бойцовский клуб",
			Genres:      []models.Genre{Genres[20]},
			Year:        1999,
			Country:     "США",
			Rating:      8.0,
			Budget:      20068472,
			Fees:        101210935,
			PremierDate: time.Date(1999, 05, 17, 0, 0, 0, 0, time.UTC),
			Duration:    139,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic13.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Гладиатор",
			Genres:      []models.Genre{Genres[8]},
			Year:        2000,
			Country:     "США",
			Rating:      8.0,
			Budget:      19630695,
			Fees:        112893295,
			PremierDate: time.Date(2000, 04, 25, 0, 0, 0, 0, time.UTC),
			Duration:    155,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic14.jpeg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Начало",
			Genres:      []models.Genre{Genres[22]},
			Year:        2010,
			Country:     "США",
			Rating:      8.0,
			Budget:      33184440,
			Fees:        102399860,
			PremierDate: time.Date(2010, 02, 07, 0, 0, 0, 0, time.UTC),
			Duration:    148,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic15.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Криминальное чтиво",
			Genres:      []models.Genre{Genres[11]},
			Year:        1994,
			Country:     "США",
			Rating:      7.9,
			Budget:      19143367,
			Fees:        104240521,
			PremierDate: time.Date(1994, 06, 07, 0, 0, 0, 0, time.UTC),
			Duration:    154,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic16.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Унесённые ветром",
			Genres:      []models.Genre{Genres[12]},
			Year:        1993,
			Country:     "США",
			Rating:      7.9,
			Budget:      9656999,
			Fees:        75217284,
			PremierDate: time.Date(1993, 12, 14, 0, 0, 0, 0, time.UTC),
			Duration:    222,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic17.jpeg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Властелин колец: Две крепости",
			Genres:      []models.Genre{Genres[23]},
			Year:        2002,
			Country:     "Новая Зеландия",
			Rating:      7.9,
			Budget:      26131034,
			Fees:        44216117,
			PremierDate: time.Date(2002, 10, 15, 0, 0, 0, 0, time.UTC),
			Duration:    179,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic18.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Достучаться до небес",
			Genres:      []models.Genre{Genres[7]},
			Year:        1997,
			Country:     "Германия",
			Rating:      7.9,
			Budget:      37831403,
			Fees:        63489538,
			PremierDate: time.Date(1997, 07, 05, 0, 0, 0, 0, time.UTC),
			Duration:    87,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic19.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Леон",
			Genres:      []models.Genre{Genres[2]},
			Year:        1994,
			Country:     "Франция",
			Rating:      7.9,
			Budget:      4424152,
			Fees:        61716151,
			PremierDate: time.Date(1994, 07, 06, 0, 0, 0, 0, time.UTC),
			Duration:    133,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic20.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Операция «Ы» и другие приключения Шурика",
			Genres:      []models.Genre{Genres[9]},
			Year:        1965,
			Country:     "СССР",
			Rating:      7.9,
			Budget:      35956424,
			Fees:        53701856,
			PremierDate: time.Date(1965, 06, 16, 0, 0, 0, 0, time.UTC),
			Duration:    95,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic21.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Список Шиндлера",
			Genres:      []models.Genre{Genres[7]},
			Year:        1993,
			Country:     "США",
			Rating:      7.8,
			Budget:      45840767,
			Fees:        143300579,
			PremierDate: time.Date(1993, 07, 25, 0, 0, 0, 0, time.UTC),
			Duration:    195,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic22.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Девчата",
			Genres:      []models.Genre{Genres[12]},
			Year:        1961,
			Country:     "СССР",
			Rating:      7.8,
			Budget:      33932401,
			Fees:        121434403,
			PremierDate: time.Date(1961, 02, 21, 0, 0, 0, 0, time.UTC),
			Duration:    92,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic23.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Темный рыцарь",
			Genres:      []models.Genre{Genres[22]},
			Year:        2008,
			Country:     "США",
			Rating:      7.8,
			Budget:      19747386,
			Fees:        57047473,
			PremierDate: time.Date(2008, 06, 16, 0, 0, 0, 0, time.UTC),
			Duration:    152,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic24.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Тайна Коко",
			Genres:      []models.Genre{Genres[15]},
			Year:        2017,
			Country:     "США",
			Rating:      7.8,
			Budget:      14298359,
			Fees:        18376774,
			PremierDate: time.Date(2017, 07, 24, 0, 0, 0, 0, time.UTC),
			Duration:    152,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic25.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Бриллиантовая рука",
			Genres:      []models.Genre{Genres[9]},
			Year:        1968,
			Country:     "СССР",
			Rating:      7.8,
			Budget:      31958089,
			Fees:        59030915,
			PremierDate: time.Date(1968, 10, 27, 0, 0, 0, 0, time.UTC),
			Duration:    94,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic26.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Брат",
			Genres:      []models.Genre{Genres[7], Genres[2]},
			Year:        1997,
			Country:     "Россия",
			Rating:      7.8,
			Budget:      5862132,
			Fees:        44747335,
			PremierDate: time.Date(1997, 02, 25, 0, 0, 0, 0, time.UTC),
			Duration:    96,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic27.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Брат 2",
			Genres:      []models.Genre{Genres[7], Genres[2]},
			Year:        2000,
			Country:     "Россия",
			Rating:      7.8,
			Budget:      5313234,
			Fees:        33775743,
			PremierDate: time.Date(2000, 03, 27, 0, 0, 0, 0, time.UTC),
			Duration:    127,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic28.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Собачье сердце",
			Genres:      []models.Genre{Genres[7], Genres[22]},
			Year:        1988,
			Country:     "СССР",
			Rating:      7.8,
			Budget:      11606663,
			Fees:        18185742,
			PremierDate: time.Date(1988, 06, 25, 0, 0, 0, 0, time.UTC),
			Duration:    136,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic29.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Пятый элемент",
			Genres:      []models.Genre{Genres[22]},
			Year:        1997,
			Country:     "Франция",
			Rating:      7.8,
			Budget:      47820996,
			Fees:        104748549,
			PremierDate: time.Date(1997, 11, 13, 0, 0, 0, 0, time.UTC),
			Duration:    126,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic30.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Крестный отец",
			Genres:      []models.Genre{Genres[7]},
			Year:        1972,
			Country:     "США",
			Rating:      7.8,
			Budget:      15916046,
			Fees:        24035867,
			PremierDate: time.Date(1972, 04, 03, 0, 0, 0, 0, time.UTC),
			Duration:    175,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic31.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Дангал",
			Genres:      []models.Genre{Genres[7]},
			Year:        2016,
			Country:     "Индия",
			Rating:      7.8,
			Budget:      10216025,
			Fees:        24069568,
			PremierDate: time.Date(2016, 10, 05, 0, 0, 0, 0, time.UTC),
			Duration:    161,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic32.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Большой куш",
			Genres:      []models.Genre{Genres[11]},
			Year:        2000,
			Country:     "Великобритания",
			Rating:      7.8,
			Budget:      7473096,
			Fees:        61001935,
			PremierDate: time.Date(2000, 06, 22, 0, 0, 0, 0, time.UTC),
			Duration:    104,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic33.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Шрэк",
			Genres:      []models.Genre{Genres[15]},
			Year:        2001,
			Country:     "США",
			Rating:      7.7,
			Budget:      33457701,
			Fees:        96128674,
			PremierDate: time.Date(2001, 05, 27, 0, 0, 0, 0, time.UTC),
			Duration:    90,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic34.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Назад в будущее",
			Genres:      []models.Genre{Genres[22]},
			Year:        1985,
			Country:     "США",
			Rating:      7.7,
			Budget:      19241918,
			Fees:        56517179,
			PremierDate: time.Date(1985, 04, 16, 0, 0, 0, 0, time.UTC),
			Duration:    116,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic35.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Дикий робот",
			Genres:      []models.Genre{Genres[15]},
			Year:        2024,
			Country:     "США",
			Rating:      7.7,
			Budget:      4468393,
			Fees:        49792138,
			PremierDate: time.Date(2024, 04, 20, 0, 0, 0, 0, time.UTC),
			Duration:    102,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic36.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Поймай меня, если сможешь",
			Genres:      []models.Genre{Genres[11]},
			Year:        2002,
			Country:     "США",
			Rating:      7.7,
			Budget:      23223014,
			Fees:        55958125,
			PremierDate: time.Date(2002, 03, 28, 0, 0, 0, 0, time.UTC),
			Duration:    141,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic37.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Карты, деньги, два ствола",
			Genres:      []models.Genre{Genres[2], Genres[21]},
			Year:        1998,
			Country:     "Великобритания",
			Rating:      7.7,
			Budget:      31963509,
			Fees:        55999481,
			PremierDate: time.Date(1998, 02, 12, 0, 0, 0, 0, time.UTC),
			Duration:    107,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic38.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Хатико: Самый верный друг",
			Genres:      []models.Genre{Genres[7]},
			Year:        2008,
			Country:     "США",
			Rating:      7.7,
			Budget:      3329561,
			Fees:        18644558,
			PremierDate: time.Date(2008, 04, 13, 0, 0, 0, 0, time.UTC),
			Duration:    89,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic39.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Кавказская пленница, или Новые приключения Шурика",
			Genres:      []models.Genre{Genres[9], Genres[19]},
			Year:        1966,
			Country:     "СССР",
			Rating:      7.7,
			Budget:      4545459,
			Fees:        20786957,
			PremierDate: time.Date(1966, 03, 05, 0, 0, 0, 0, time.UTC),
			Duration:    82,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic40.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Трасса 60",
			Genres:      []models.Genre{Genres[23], Genres[18]},
			Year:        2001,
			Country:     "Канада",
			Rating:      7.6,
			Budget:      14962443,
			Fees:        83078166,
			PremierDate: time.Date(2001, 12, 01, 0, 0, 0, 0, time.UTC),
			Duration:    106,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic41.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Титаник",
			Genres:      []models.Genre{Genres[12], Genres[17]},
			Year:        1997,
			Country:     "США",
			Rating:      7.6,
			Budget:      10495756,
			Fees:        30975570,
			PremierDate: time.Date(1997, 12, 14, 0, 0, 0, 0, time.UTC),
			Duration:    194,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic42.jpg",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Матрица",
			Genres:      []models.Genre{Genres[22], Genres[16]},
			Year:        1999,
			Country:     "США",
			Rating:      7.6,
			Budget:      19748252,
			Fees:        61583239,
			PremierDate: time.Date(1999, 01, 01, 0, 0, 0, 0, time.UTC),
			Duration:    196,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic43.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Гарри Поттер и философский камень",
			Genres:      []models.Genre{Genres[23], Genres[13], Genres[14]},
			Year:        2001,
			Country:     "Великобритания",
			Rating:      7.6,
			Budget:      37877517,
			Fees:        42345006,
			PremierDate: time.Date(2001, 10, 10, 0, 0, 0, 0, time.UTC),
			Duration:    212,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic44.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "В августе 44-го",
			Genres:      []models.Genre{Genres[4]},
			Year:        2001,
			Country:     "Россия",
			Rating:      7.6,
			Budget:      48242995,
			Fees:        58836254,
			PremierDate: time.Date(2001, 07, 17, 0, 0, 0, 0, time.UTC),
			Duration:    118,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic45.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "...А зори здесь тихие",
			Genres:      []models.Genre{Genres[7]},
			Year:        1972,
			Country:     "СССР",
			Rating:      7.6,
			Budget:      24396798,
			Fees:        95215190,
			PremierDate: time.Date(1972, 05, 22, 0, 0, 0, 0, time.UTC),
			Duration:    160,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic46.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Пианист",
			Genres:      []models.Genre{Genres[7], Genres[10]},
			Year:        2002,
			Country:     "Франция",
			Rating:      7.6,
			Budget:      16910386,
			Fees:        67330630,
			PremierDate: time.Date(2002, 06, 15, 0, 0, 0, 0, time.UTC),
			Duration:    149,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic47.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Иди и смотри",
			Genres:      []models.Genre{Genres[8], Genres[6]},
			Year:        1985,
			Country:     "СССР",
			Rating:      7.6,
			Budget:      36331258,
			Fees:        132241739,
			PremierDate: time.Date(1985, 12, 26, 0, 0, 0, 0, time.UTC),
			Duration:    136,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic48.png",
		},
		{
			ID:          uuid.Must(uuid.NewV4(), nil),
			Title:       "Джанго освобожденный",
			Genres:      []models.Genre{Genres[3], Genres[5]},
			Year:        2012,
			Country:     "США",
			Rating:      7.6,
			Budget:      32076835,
			Fees:        60775935,
			PremierDate: time.Date(2012, 06, 18, 0, 0, 0, 0, time.UTC),
			Duration:    165,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
			Cover:       "/static/films/pic49.png",
		},
	}
}
