// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/films/delivery/grpc/gen/films_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/films/delivery/grpc/gen/films_grpc.pb.go -destination=internal/pkg/films/mocks/grpc_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gen "kinopoisk/internal/pkg/films/delivery/grpc/gen"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockFilmsClient is a mock of FilmsClient interface.
type MockFilmsClient struct {
	ctrl     *gomock.Controller
	recorder *MockFilmsClientMockRecorder
	isgomock struct{}
}

// MockFilmsClientMockRecorder is the mock recorder for MockFilmsClient.
type MockFilmsClientMockRecorder struct {
	mock *MockFilmsClient
}

// NewMockFilmsClient creates a new mock instance.
func NewMockFilmsClient(ctrl *gomock.Controller) *MockFilmsClient {
	mock := &MockFilmsClient{ctrl: ctrl}
	mock.recorder = &MockFilmsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmsClient) EXPECT() *MockFilmsClientMockRecorder {
	return m.recorder
}

// GetActor mocks base method.
func (m *MockFilmsClient) GetActor(ctx context.Context, in *gen.GetActorRequest, opts ...grpc.CallOption) (*gen.GetActorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetActor", varargs...)
	ret0, _ := ret[0].(*gen.GetActorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActor indicates an expected call of GetActor.
func (mr *MockFilmsClientMockRecorder) GetActor(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActor", reflect.TypeOf((*MockFilmsClient)(nil).GetActor), varargs...)
}

// GetCompilation mocks base method.
func (m *MockFilmsClient) GetCompilation(ctx context.Context, in *gen.GetCompilationRequest, opts ...grpc.CallOption) (*gen.GetCompilationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCompilation", varargs...)
	ret0, _ := ret[0].(*gen.GetCompilationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilation indicates an expected call of GetCompilation.
func (mr *MockFilmsClientMockRecorder) GetCompilation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilation", reflect.TypeOf((*MockFilmsClient)(nil).GetCompilation), varargs...)
}

// GetCompilations mocks base method.
func (m *MockFilmsClient) GetCompilations(ctx context.Context, in *gen.GetCompilationsRequest, opts ...grpc.CallOption) (*gen.GetCompilationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCompilations", varargs...)
	ret0, _ := ret[0].(*gen.GetCompilationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilations indicates an expected call of GetCompilations.
func (mr *MockFilmsClientMockRecorder) GetCompilations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilations", reflect.TypeOf((*MockFilmsClient)(nil).GetCompilations), varargs...)
}

// GetFavFilms mocks base method.
func (m *MockFilmsClient) GetFavFilms(ctx context.Context, in *gen.GetFavFilmsRequest, opts ...grpc.CallOption) (*gen.GetFavFilmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavFilms", varargs...)
	ret0, _ := ret[0].(*gen.GetFavFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavFilms indicates an expected call of GetFavFilms.
func (mr *MockFilmsClientMockRecorder) GetFavFilms(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavFilms", reflect.TypeOf((*MockFilmsClient)(nil).GetFavFilms), varargs...)
}

// GetFilm mocks base method.
func (m *MockFilmsClient) GetFilm(ctx context.Context, in *gen.GetFilmRequest, opts ...grpc.CallOption) (*gen.GetFilmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilm", varargs...)
	ret0, _ := ret[0].(*gen.GetFilmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilm indicates an expected call of GetFilm.
func (mr *MockFilmsClientMockRecorder) GetFilm(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilm", reflect.TypeOf((*MockFilmsClient)(nil).GetFilm), varargs...)
}

// GetFilmFeedbacks mocks base method.
func (m *MockFilmsClient) GetFilmFeedbacks(ctx context.Context, in *gen.GetFilmFeedbacksRequest, opts ...grpc.CallOption) (*gen.GetFilmFeedbacksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilmFeedbacks", varargs...)
	ret0, _ := ret[0].(*gen.GetFilmFeedbacksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmFeedbacks indicates an expected call of GetFilmFeedbacks.
func (mr *MockFilmsClientMockRecorder) GetFilmFeedbacks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmFeedbacks", reflect.TypeOf((*MockFilmsClient)(nil).GetFilmFeedbacks), varargs...)
}

// GetFilms mocks base method.
func (m *MockFilmsClient) GetFilms(ctx context.Context, in *gen.GetFilmsRequest, opts ...grpc.CallOption) (*gen.GetFilmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilms", varargs...)
	ret0, _ := ret[0].(*gen.GetFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilms indicates an expected call of GetFilms.
func (mr *MockFilmsClientMockRecorder) GetFilms(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilms", reflect.TypeOf((*MockFilmsClient)(nil).GetFilms), varargs...)
}

// GetFilmsByActor mocks base method.
func (m *MockFilmsClient) GetFilmsByActor(ctx context.Context, in *gen.GetFilmsByActorRequest, opts ...grpc.CallOption) (*gen.GetFilmsByActorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilmsByActor", varargs...)
	ret0, _ := ret[0].(*gen.GetFilmsByActorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByActor indicates an expected call of GetFilmsByActor.
func (mr *MockFilmsClientMockRecorder) GetFilmsByActor(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByActor", reflect.TypeOf((*MockFilmsClient)(nil).GetFilmsByActor), varargs...)
}

// GetFilmsByCompilation mocks base method.
func (m *MockFilmsClient) GetFilmsByCompilation(ctx context.Context, in *gen.GetFilmsByCompilationRequest, opts ...grpc.CallOption) (*gen.GetFilmsByCompilationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilmsByCompilation", varargs...)
	ret0, _ := ret[0].(*gen.GetFilmsByCompilationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByCompilation indicates an expected call of GetFilmsByCompilation.
func (mr *MockFilmsClientMockRecorder) GetFilmsByCompilation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByCompilation", reflect.TypeOf((*MockFilmsClient)(nil).GetFilmsByCompilation), varargs...)
}

// GetFilmsByGenre mocks base method.
func (m *MockFilmsClient) GetFilmsByGenre(ctx context.Context, in *gen.GetFilmsByGenreRequest, opts ...grpc.CallOption) (*gen.GetFilmsByGenreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilmsByGenre", varargs...)
	ret0, _ := ret[0].(*gen.GetFilmsByGenreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByGenre indicates an expected call of GetFilmsByGenre.
func (mr *MockFilmsClientMockRecorder) GetFilmsByGenre(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByGenre", reflect.TypeOf((*MockFilmsClient)(nil).GetFilmsByGenre), varargs...)
}

// GetFilmsForCalendar mocks base method.
func (m *MockFilmsClient) GetFilmsForCalendar(ctx context.Context, in *gen.GetFilmsForCalendarRequest, opts ...grpc.CallOption) (*gen.GetFilmsForCalendarResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilmsForCalendar", varargs...)
	ret0, _ := ret[0].(*gen.GetFilmsForCalendarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsForCalendar indicates an expected call of GetFilmsForCalendar.
func (mr *MockFilmsClientMockRecorder) GetFilmsForCalendar(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsForCalendar", reflect.TypeOf((*MockFilmsClient)(nil).GetFilmsForCalendar), varargs...)
}

// GetGenre mocks base method.
func (m *MockFilmsClient) GetGenre(ctx context.Context, in *gen.GetGenreRequest, opts ...grpc.CallOption) (*gen.GetGenreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGenre", varargs...)
	ret0, _ := ret[0].(*gen.GetGenreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenre indicates an expected call of GetGenre.
func (mr *MockFilmsClientMockRecorder) GetGenre(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenre", reflect.TypeOf((*MockFilmsClient)(nil).GetGenre), varargs...)
}

// GetGenres mocks base method.
func (m *MockFilmsClient) GetGenres(ctx context.Context, in *gen.GetGenresRequest, opts ...grpc.CallOption) (*gen.GetGenresResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGenres", varargs...)
	ret0, _ := ret[0].(*gen.GetGenresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenres indicates an expected call of GetGenres.
func (mr *MockFilmsClientMockRecorder) GetGenres(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenres", reflect.TypeOf((*MockFilmsClient)(nil).GetGenres), varargs...)
}

// GetPromoFilm mocks base method.
func (m *MockFilmsClient) GetPromoFilm(ctx context.Context, in *gen.EmptyRequest, opts ...grpc.CallOption) (*gen.GetPromoFilmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPromoFilm", varargs...)
	ret0, _ := ret[0].(*gen.GetPromoFilmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoFilm indicates an expected call of GetPromoFilm.
func (mr *MockFilmsClientMockRecorder) GetPromoFilm(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoFilm", reflect.TypeOf((*MockFilmsClient)(nil).GetPromoFilm), varargs...)
}

// GetSimilarFilms mocks base method.
func (m *MockFilmsClient) GetSimilarFilms(ctx context.Context, in *gen.GetSimilarFilmsRequest, opts ...grpc.CallOption) (*gen.GetSimilarFilmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSimilarFilms", varargs...)
	ret0, _ := ret[0].(*gen.GetSimilarFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimilarFilms indicates an expected call of GetSimilarFilms.
func (mr *MockFilmsClientMockRecorder) GetSimilarFilms(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimilarFilms", reflect.TypeOf((*MockFilmsClient)(nil).GetSimilarFilms), varargs...)
}

// RemoveFilm mocks base method.
func (m *MockFilmsClient) RemoveFilm(ctx context.Context, in *gen.RemoveFilmRequest, opts ...grpc.CallOption) (*gen.GetFavFilmsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFilm", varargs...)
	ret0, _ := ret[0].(*gen.GetFavFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFilm indicates an expected call of RemoveFilm.
func (mr *MockFilmsClientMockRecorder) RemoveFilm(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilm", reflect.TypeOf((*MockFilmsClient)(nil).RemoveFilm), varargs...)
}

// SaveFilm mocks base method.
func (m *MockFilmsClient) SaveFilm(ctx context.Context, in *gen.SaveFilmRequest, opts ...grpc.CallOption) (*gen.EmptyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveFilm", varargs...)
	ret0, _ := ret[0].(*gen.EmptyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFilm indicates an expected call of SaveFilm.
func (mr *MockFilmsClientMockRecorder) SaveFilm(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFilm", reflect.TypeOf((*MockFilmsClient)(nil).SaveFilm), varargs...)
}

// SendFeedback mocks base method.
func (m *MockFilmsClient) SendFeedback(ctx context.Context, in *gen.SendFeedbackRequest, opts ...grpc.CallOption) (*gen.SendFeedbackResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendFeedback", varargs...)
	ret0, _ := ret[0].(*gen.SendFeedbackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFeedback indicates an expected call of SendFeedback.
func (mr *MockFilmsClientMockRecorder) SendFeedback(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFeedback", reflect.TypeOf((*MockFilmsClient)(nil).SendFeedback), varargs...)
}

// SetRating mocks base method.
func (m *MockFilmsClient) SetRating(ctx context.Context, in *gen.SetRatingRequest, opts ...grpc.CallOption) (*gen.SetRatingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetRating", varargs...)
	ret0, _ := ret[0].(*gen.SetRatingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRating indicates an expected call of SetRating.
func (mr *MockFilmsClientMockRecorder) SetRating(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockFilmsClient)(nil).SetRating), varargs...)
}

// SiteMap mocks base method.
func (m *MockFilmsClient) SiteMap(ctx context.Context, in *gen.EmptyRequest, opts ...grpc.CallOption) (*gen.SiteMapResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SiteMap", varargs...)
	ret0, _ := ret[0].(*gen.SiteMapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SiteMap indicates an expected call of SiteMap.
func (mr *MockFilmsClientMockRecorder) SiteMap(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SiteMap", reflect.TypeOf((*MockFilmsClient)(nil).SiteMap), varargs...)
}

// ValidateUser mocks base method.
func (m *MockFilmsClient) ValidateUser(ctx context.Context, in *gen.ValidateUserRequest, opts ...grpc.CallOption) (*gen.ValidateUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidateUser", varargs...)
	ret0, _ := ret[0].(*gen.ValidateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUser indicates an expected call of ValidateUser.
func (mr *MockFilmsClientMockRecorder) ValidateUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUser", reflect.TypeOf((*MockFilmsClient)(nil).ValidateUser), varargs...)
}

// MockFilmsServer is a mock of FilmsServer interface.
type MockFilmsServer struct {
	ctrl     *gomock.Controller
	recorder *MockFilmsServerMockRecorder
	isgomock struct{}
}

// MockFilmsServerMockRecorder is the mock recorder for MockFilmsServer.
type MockFilmsServerMockRecorder struct {
	mock *MockFilmsServer
}

// NewMockFilmsServer creates a new mock instance.
func NewMockFilmsServer(ctrl *gomock.Controller) *MockFilmsServer {
	mock := &MockFilmsServer{ctrl: ctrl}
	mock.recorder = &MockFilmsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmsServer) EXPECT() *MockFilmsServerMockRecorder {
	return m.recorder
}

// GetActor mocks base method.
func (m *MockFilmsServer) GetActor(arg0 context.Context, arg1 *gen.GetActorRequest) (*gen.GetActorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActor", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetActorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActor indicates an expected call of GetActor.
func (mr *MockFilmsServerMockRecorder) GetActor(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActor", reflect.TypeOf((*MockFilmsServer)(nil).GetActor), arg0, arg1)
}

// GetCompilation mocks base method.
func (m *MockFilmsServer) GetCompilation(arg0 context.Context, arg1 *gen.GetCompilationRequest) (*gen.GetCompilationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompilation", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetCompilationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilation indicates an expected call of GetCompilation.
func (mr *MockFilmsServerMockRecorder) GetCompilation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilation", reflect.TypeOf((*MockFilmsServer)(nil).GetCompilation), arg0, arg1)
}

// GetCompilations mocks base method.
func (m *MockFilmsServer) GetCompilations(arg0 context.Context, arg1 *gen.GetCompilationsRequest) (*gen.GetCompilationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompilations", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetCompilationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompilations indicates an expected call of GetCompilations.
func (mr *MockFilmsServerMockRecorder) GetCompilations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompilations", reflect.TypeOf((*MockFilmsServer)(nil).GetCompilations), arg0, arg1)
}

// GetFavFilms mocks base method.
func (m *MockFilmsServer) GetFavFilms(arg0 context.Context, arg1 *gen.GetFavFilmsRequest) (*gen.GetFavFilmsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavFilms", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFavFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavFilms indicates an expected call of GetFavFilms.
func (mr *MockFilmsServerMockRecorder) GetFavFilms(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavFilms", reflect.TypeOf((*MockFilmsServer)(nil).GetFavFilms), arg0, arg1)
}

// GetFilm mocks base method.
func (m *MockFilmsServer) GetFilm(arg0 context.Context, arg1 *gen.GetFilmRequest) (*gen.GetFilmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilm", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFilmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilm indicates an expected call of GetFilm.
func (mr *MockFilmsServerMockRecorder) GetFilm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilm", reflect.TypeOf((*MockFilmsServer)(nil).GetFilm), arg0, arg1)
}

// GetFilmFeedbacks mocks base method.
func (m *MockFilmsServer) GetFilmFeedbacks(arg0 context.Context, arg1 *gen.GetFilmFeedbacksRequest) (*gen.GetFilmFeedbacksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmFeedbacks", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFilmFeedbacksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmFeedbacks indicates an expected call of GetFilmFeedbacks.
func (mr *MockFilmsServerMockRecorder) GetFilmFeedbacks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmFeedbacks", reflect.TypeOf((*MockFilmsServer)(nil).GetFilmFeedbacks), arg0, arg1)
}

// GetFilms mocks base method.
func (m *MockFilmsServer) GetFilms(arg0 context.Context, arg1 *gen.GetFilmsRequest) (*gen.GetFilmsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilms", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilms indicates an expected call of GetFilms.
func (mr *MockFilmsServerMockRecorder) GetFilms(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilms", reflect.TypeOf((*MockFilmsServer)(nil).GetFilms), arg0, arg1)
}

// GetFilmsByActor mocks base method.
func (m *MockFilmsServer) GetFilmsByActor(arg0 context.Context, arg1 *gen.GetFilmsByActorRequest) (*gen.GetFilmsByActorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByActor", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFilmsByActorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByActor indicates an expected call of GetFilmsByActor.
func (mr *MockFilmsServerMockRecorder) GetFilmsByActor(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByActor", reflect.TypeOf((*MockFilmsServer)(nil).GetFilmsByActor), arg0, arg1)
}

// GetFilmsByCompilation mocks base method.
func (m *MockFilmsServer) GetFilmsByCompilation(arg0 context.Context, arg1 *gen.GetFilmsByCompilationRequest) (*gen.GetFilmsByCompilationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByCompilation", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFilmsByCompilationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByCompilation indicates an expected call of GetFilmsByCompilation.
func (mr *MockFilmsServerMockRecorder) GetFilmsByCompilation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByCompilation", reflect.TypeOf((*MockFilmsServer)(nil).GetFilmsByCompilation), arg0, arg1)
}

// GetFilmsByGenre mocks base method.
func (m *MockFilmsServer) GetFilmsByGenre(arg0 context.Context, arg1 *gen.GetFilmsByGenreRequest) (*gen.GetFilmsByGenreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByGenre", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFilmsByGenreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByGenre indicates an expected call of GetFilmsByGenre.
func (mr *MockFilmsServerMockRecorder) GetFilmsByGenre(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByGenre", reflect.TypeOf((*MockFilmsServer)(nil).GetFilmsByGenre), arg0, arg1)
}

// GetFilmsForCalendar mocks base method.
func (m *MockFilmsServer) GetFilmsForCalendar(arg0 context.Context, arg1 *gen.GetFilmsForCalendarRequest) (*gen.GetFilmsForCalendarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsForCalendar", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFilmsForCalendarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsForCalendar indicates an expected call of GetFilmsForCalendar.
func (mr *MockFilmsServerMockRecorder) GetFilmsForCalendar(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsForCalendar", reflect.TypeOf((*MockFilmsServer)(nil).GetFilmsForCalendar), arg0, arg1)
}

// GetGenre mocks base method.
func (m *MockFilmsServer) GetGenre(arg0 context.Context, arg1 *gen.GetGenreRequest) (*gen.GetGenreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenre", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetGenreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenre indicates an expected call of GetGenre.
func (mr *MockFilmsServerMockRecorder) GetGenre(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenre", reflect.TypeOf((*MockFilmsServer)(nil).GetGenre), arg0, arg1)
}

// GetGenres mocks base method.
func (m *MockFilmsServer) GetGenres(arg0 context.Context, arg1 *gen.GetGenresRequest) (*gen.GetGenresResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenres", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetGenresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenres indicates an expected call of GetGenres.
func (mr *MockFilmsServerMockRecorder) GetGenres(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenres", reflect.TypeOf((*MockFilmsServer)(nil).GetGenres), arg0, arg1)
}

// GetPromoFilm mocks base method.
func (m *MockFilmsServer) GetPromoFilm(arg0 context.Context, arg1 *gen.EmptyRequest) (*gen.GetPromoFilmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoFilm", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetPromoFilmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoFilm indicates an expected call of GetPromoFilm.
func (mr *MockFilmsServerMockRecorder) GetPromoFilm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoFilm", reflect.TypeOf((*MockFilmsServer)(nil).GetPromoFilm), arg0, arg1)
}

// GetSimilarFilms mocks base method.
func (m *MockFilmsServer) GetSimilarFilms(arg0 context.Context, arg1 *gen.GetSimilarFilmsRequest) (*gen.GetSimilarFilmsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimilarFilms", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetSimilarFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimilarFilms indicates an expected call of GetSimilarFilms.
func (mr *MockFilmsServerMockRecorder) GetSimilarFilms(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimilarFilms", reflect.TypeOf((*MockFilmsServer)(nil).GetSimilarFilms), arg0, arg1)
}

// RemoveFilm mocks base method.
func (m *MockFilmsServer) RemoveFilm(arg0 context.Context, arg1 *gen.RemoveFilmRequest) (*gen.GetFavFilmsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFilm", arg0, arg1)
	ret0, _ := ret[0].(*gen.GetFavFilmsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFilm indicates an expected call of RemoveFilm.
func (mr *MockFilmsServerMockRecorder) RemoveFilm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilm", reflect.TypeOf((*MockFilmsServer)(nil).RemoveFilm), arg0, arg1)
}

// SaveFilm mocks base method.
func (m *MockFilmsServer) SaveFilm(arg0 context.Context, arg1 *gen.SaveFilmRequest) (*gen.EmptyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFilm", arg0, arg1)
	ret0, _ := ret[0].(*gen.EmptyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFilm indicates an expected call of SaveFilm.
func (mr *MockFilmsServerMockRecorder) SaveFilm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFilm", reflect.TypeOf((*MockFilmsServer)(nil).SaveFilm), arg0, arg1)
}

// SendFeedback mocks base method.
func (m *MockFilmsServer) SendFeedback(arg0 context.Context, arg1 *gen.SendFeedbackRequest) (*gen.SendFeedbackResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFeedback", arg0, arg1)
	ret0, _ := ret[0].(*gen.SendFeedbackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFeedback indicates an expected call of SendFeedback.
func (mr *MockFilmsServerMockRecorder) SendFeedback(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFeedback", reflect.TypeOf((*MockFilmsServer)(nil).SendFeedback), arg0, arg1)
}

// SetRating mocks base method.
func (m *MockFilmsServer) SetRating(arg0 context.Context, arg1 *gen.SetRatingRequest) (*gen.SetRatingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", arg0, arg1)
	ret0, _ := ret[0].(*gen.SetRatingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRating indicates an expected call of SetRating.
func (mr *MockFilmsServerMockRecorder) SetRating(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockFilmsServer)(nil).SetRating), arg0, arg1)
}

// SiteMap mocks base method.
func (m *MockFilmsServer) SiteMap(arg0 context.Context, arg1 *gen.EmptyRequest) (*gen.SiteMapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SiteMap", arg0, arg1)
	ret0, _ := ret[0].(*gen.SiteMapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SiteMap indicates an expected call of SiteMap.
func (mr *MockFilmsServerMockRecorder) SiteMap(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SiteMap", reflect.TypeOf((*MockFilmsServer)(nil).SiteMap), arg0, arg1)
}

// ValidateUser mocks base method.
func (m *MockFilmsServer) ValidateUser(arg0 context.Context, arg1 *gen.ValidateUserRequest) (*gen.ValidateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUser", arg0, arg1)
	ret0, _ := ret[0].(*gen.ValidateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUser indicates an expected call of ValidateUser.
func (mr *MockFilmsServerMockRecorder) ValidateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUser", reflect.TypeOf((*MockFilmsServer)(nil).ValidateUser), arg0, arg1)
}

// mustEmbedUnimplementedFilmsServer mocks base method.
func (m *MockFilmsServer) mustEmbedUnimplementedFilmsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFilmsServer")
}

// mustEmbedUnimplementedFilmsServer indicates an expected call of mustEmbedUnimplementedFilmsServer.
func (mr *MockFilmsServerMockRecorder) mustEmbedUnimplementedFilmsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFilmsServer", reflect.TypeOf((*MockFilmsServer)(nil).mustEmbedUnimplementedFilmsServer))
}

// MockUnsafeFilmsServer is a mock of UnsafeFilmsServer interface.
type MockUnsafeFilmsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeFilmsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeFilmsServerMockRecorder is the mock recorder for MockUnsafeFilmsServer.
type MockUnsafeFilmsServerMockRecorder struct {
	mock *MockUnsafeFilmsServer
}

// NewMockUnsafeFilmsServer creates a new mock instance.
func NewMockUnsafeFilmsServer(ctrl *gomock.Controller) *MockUnsafeFilmsServer {
	mock := &MockUnsafeFilmsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeFilmsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeFilmsServer) EXPECT() *MockUnsafeFilmsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedFilmsServer mocks base method.
func (m *MockUnsafeFilmsServer) mustEmbedUnimplementedFilmsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFilmsServer")
}

// mustEmbedUnimplementedFilmsServer indicates an expected call of mustEmbedUnimplementedFilmsServer.
func (mr *MockUnsafeFilmsServerMockRecorder) mustEmbedUnimplementedFilmsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFilmsServer", reflect.TypeOf((*MockUnsafeFilmsServer)(nil).mustEmbedUnimplementedFilmsServer))
}
