// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/films/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/films/interfaces.go -destination=internal/pkg/films/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"

	uuid "github.com/satori/go.uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFilmUsecase is a mock of FilmUsecase interface.
type MockFilmUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFilmUsecaseMockRecorder
	isgomock struct{}
}

// MockFilmUsecaseMockRecorder is the mock recorder for MockFilmUsecase.
type MockFilmUsecaseMockRecorder struct {
	mock *MockFilmUsecase
}

// NewMockFilmUsecase creates a new mock instance.
func NewMockFilmUsecase(ctrl *gomock.Controller) *MockFilmUsecase {
	mock := &MockFilmUsecase{ctrl: ctrl}
	mock.recorder = &MockFilmUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmUsecase) EXPECT() *MockFilmUsecaseMockRecorder {
	return m.recorder
}

// GetFilm mocks base method.
func (m *MockFilmUsecase) GetFilm(ctx context.Context, id uuid.UUID) (models.FilmPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilm", ctx, id)
	ret0, _ := ret[0].(models.FilmPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilm indicates an expected call of GetFilm.
func (mr *MockFilmUsecaseMockRecorder) GetFilm(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilm", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilm), ctx, id)
}

// GetFilmFeedbacks mocks base method.
func (m *MockFilmUsecase) GetFilmFeedbacks(ctx context.Context, id uuid.UUID, pager models.Pager) ([]models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmFeedbacks", ctx, id, pager)
	ret0, _ := ret[0].([]models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmFeedbacks indicates an expected call of GetFilmFeedbacks.
func (mr *MockFilmUsecaseMockRecorder) GetFilmFeedbacks(ctx, id, pager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmFeedbacks", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilmFeedbacks), ctx, id, pager)
}

// GetFilms mocks base method.
func (m *MockFilmUsecase) GetFilms(ctx context.Context, pager models.Pager) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilms", ctx, pager)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilms indicates an expected call of GetFilms.
func (mr *MockFilmUsecaseMockRecorder) GetFilms(ctx, pager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilms", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilms), ctx, pager)
}

// GetPromoFilm mocks base method.
func (m *MockFilmUsecase) GetPromoFilm(ctx context.Context) (models.PromoFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoFilm", ctx)
	ret0, _ := ret[0].(models.PromoFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoFilm indicates an expected call of GetPromoFilm.
func (mr *MockFilmUsecaseMockRecorder) GetPromoFilm(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoFilm", reflect.TypeOf((*MockFilmUsecase)(nil).GetPromoFilm), ctx)
}

// SendFeedback mocks base method.
func (m *MockFilmUsecase) SendFeedback(ctx context.Context, req models.FilmFeedbackInput, filmID uuid.UUID) (models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFeedback", ctx, req, filmID)
	ret0, _ := ret[0].(models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFeedback indicates an expected call of SendFeedback.
func (mr *MockFilmUsecaseMockRecorder) SendFeedback(ctx, req, filmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFeedback", reflect.TypeOf((*MockFilmUsecase)(nil).SendFeedback), ctx, req, filmID)
}

// SetRating mocks base method.
func (m *MockFilmUsecase) SetRating(ctx context.Context, req models.FilmFeedbackInput, filmID uuid.UUID) (models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", ctx, req, filmID)
	ret0, _ := ret[0].(models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRating indicates an expected call of SetRating.
func (mr *MockFilmUsecaseMockRecorder) SetRating(ctx, req, filmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockFilmUsecase)(nil).SetRating), ctx, req, filmID)
}

// ValidateAndGetUser mocks base method.
func (m *MockFilmUsecase) ValidateAndGetUser(ctx context.Context, token string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndGetUser", ctx, token)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndGetUser indicates an expected call of ValidateAndGetUser.
func (mr *MockFilmUsecaseMockRecorder) ValidateAndGetUser(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndGetUser", reflect.TypeOf((*MockFilmUsecase)(nil).ValidateAndGetUser), ctx, token)
}

// MockFilmRepo is a mock of FilmRepo interface.
type MockFilmRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFilmRepoMockRecorder
	isgomock struct{}
}

// MockFilmRepoMockRecorder is the mock recorder for MockFilmRepo.
type MockFilmRepoMockRecorder struct {
	mock *MockFilmRepo
}

// NewMockFilmRepo creates a new mock instance.
func NewMockFilmRepo(ctrl *gomock.Controller) *MockFilmRepo {
	mock := &MockFilmRepo{ctrl: ctrl}
	mock.recorder = &MockFilmRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmRepo) EXPECT() *MockFilmRepoMockRecorder {
	return m.recorder
}

// CheckUserFeedbackExists mocks base method.
func (m *MockFilmRepo) CheckUserFeedbackExists(ctx context.Context, userID, filmID uuid.UUID) (models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserFeedbackExists", ctx, userID, filmID)
	ret0, _ := ret[0].(models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserFeedbackExists indicates an expected call of CheckUserFeedbackExists.
func (mr *MockFilmRepoMockRecorder) CheckUserFeedbackExists(ctx, userID, filmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserFeedbackExists", reflect.TypeOf((*MockFilmRepo)(nil).CheckUserFeedbackExists), ctx, userID, filmID)
}

// CreateFeedback mocks base method.
func (m *MockFilmRepo) CreateFeedback(ctx context.Context, feedback models.FilmFeedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeedback", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFeedback indicates an expected call of CreateFeedback.
func (mr *MockFilmRepoMockRecorder) CreateFeedback(ctx, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeedback", reflect.TypeOf((*MockFilmRepo)(nil).CreateFeedback), ctx, feedback)
}

// GetFilmAvgRating mocks base method.
func (m *MockFilmRepo) GetFilmAvgRating(ctx context.Context, filmID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmAvgRating", ctx, filmID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmAvgRating indicates an expected call of GetFilmAvgRating.
func (mr *MockFilmRepoMockRecorder) GetFilmAvgRating(ctx, filmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmAvgRating", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmAvgRating), ctx, filmID)
}

// GetFilmByID mocks base method.
func (m *MockFilmRepo) GetFilmByID(ctx context.Context, id uuid.UUID) (models.Film, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmByID", ctx, id)
	ret0, _ := ret[0].(models.Film)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmByID indicates an expected call of GetFilmByID.
func (mr *MockFilmRepoMockRecorder) GetFilmByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmByID", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmByID), ctx, id)
}

// GetFilmFeedbacks mocks base method.
func (m *MockFilmRepo) GetFilmFeedbacks(ctx context.Context, filmID uuid.UUID, limit, offset int) ([]models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmFeedbacks", ctx, filmID, limit, offset)
	ret0, _ := ret[0].([]models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmFeedbacks indicates an expected call of GetFilmFeedbacks.
func (mr *MockFilmRepoMockRecorder) GetFilmFeedbacks(ctx, filmID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmFeedbacks", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmFeedbacks), ctx, filmID, limit, offset)
}

// GetFilmPage mocks base method.
func (m *MockFilmRepo) GetFilmPage(ctx context.Context, filmID uuid.UUID) (models.FilmPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmPage", ctx, filmID)
	ret0, _ := ret[0].(models.FilmPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmPage indicates an expected call of GetFilmPage.
func (mr *MockFilmRepoMockRecorder) GetFilmPage(ctx, filmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmPage", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmPage), ctx, filmID)
}

// GetFilmsWithPagination mocks base method.
func (m *MockFilmRepo) GetFilmsWithPagination(ctx context.Context, limit, offset int) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsWithPagination", ctx, limit, offset)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsWithPagination indicates an expected call of GetFilmsWithPagination.
func (mr *MockFilmRepoMockRecorder) GetFilmsWithPagination(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsWithPagination", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmsWithPagination), ctx, limit, offset)
}

// GetGenreTitle mocks base method.
func (m *MockFilmRepo) GetGenreTitle(ctx context.Context, genreID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenreTitle", ctx, genreID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenreTitle indicates an expected call of GetGenreTitle.
func (mr *MockFilmRepoMockRecorder) GetGenreTitle(ctx, genreID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenreTitle", reflect.TypeOf((*MockFilmRepo)(nil).GetGenreTitle), ctx, genreID)
}

// GetPromoFilmByID mocks base method.
func (m *MockFilmRepo) GetPromoFilmByID(ctx context.Context, id uuid.UUID) (models.PromoFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoFilmByID", ctx, id)
	ret0, _ := ret[0].(models.PromoFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoFilmByID indicates an expected call of GetPromoFilmByID.
func (mr *MockFilmRepoMockRecorder) GetPromoFilmByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoFilmByID", reflect.TypeOf((*MockFilmRepo)(nil).GetPromoFilmByID), ctx, id)
}

// GetUserByLogin mocks base method.
func (m *MockFilmRepo) GetUserByLogin(ctx context.Context, login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockFilmRepoMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockFilmRepo)(nil).GetUserByLogin), ctx, login)
}

// SetRating mocks base method.
func (m *MockFilmRepo) SetRating(ctx context.Context, feedback models.FilmFeedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRating indicates an expected call of SetRating.
func (mr *MockFilmRepoMockRecorder) SetRating(ctx, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockFilmRepo)(nil).SetRating), ctx, feedback)
}

// UpdateFeedback mocks base method.
func (m *MockFilmRepo) UpdateFeedback(ctx context.Context, feedback models.FilmFeedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeedback", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeedback indicates an expected call of UpdateFeedback.
func (mr *MockFilmRepoMockRecorder) UpdateFeedback(ctx, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeedback", reflect.TypeOf((*MockFilmRepo)(nil).UpdateFeedback), ctx, feedback)
}
