// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/films/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"
	time "time"

	uuid "github.com/satori/go.uuid"
	"go.uber.org/mock/gomock"
)

// MockFilmUsecase is a mock of FilmUsecase interface.
type MockFilmUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFilmUsecaseMockRecorder
}

// MockFilmUsecaseMockRecorder is the mock recorder for MockFilmUsecase.
type MockFilmUsecaseMockRecorder struct {
	mock *MockFilmUsecase
}

// NewMockFilmUsecase creates a new mock instance.
func NewMockFilmUsecase(ctrl *gomock.Controller) *MockFilmUsecase {
	mock := &MockFilmUsecase{ctrl: ctrl}
	mock.recorder = &MockFilmUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmUsecase) EXPECT() *MockFilmUsecaseMockRecorder {
	return m.recorder
}

// GetFilm mocks base method.
func (m *MockFilmUsecase) GetFilm(ctx context.Context, id, userID uuid.UUID) (models.FilmPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilm", ctx, id, userID)
	ret0, _ := ret[0].(models.FilmPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilm indicates an expected call of GetFilm.
func (mr *MockFilmUsecaseMockRecorder) GetFilm(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilm", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilm), ctx, id, userID)
}

// GetFilmFeedbacks mocks base method.
func (m *MockFilmUsecase) GetFilmFeedbacks(ctx context.Context, id, userID uuid.UUID, pager models.Pager) ([]models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmFeedbacks", ctx, id, userID, pager)
	ret0, _ := ret[0].([]models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmFeedbacks indicates an expected call of GetFilmFeedbacks.
func (mr *MockFilmUsecaseMockRecorder) GetFilmFeedbacks(ctx, id, userID, pager interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmFeedbacks", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilmFeedbacks), ctx, id, userID, pager)
}

// GetFilms mocks base method.
func (m *MockFilmUsecase) GetFilms(ctx context.Context, pager models.CursorPager) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilms", ctx, pager)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilms indicates an expected call of GetFilms.
func (mr *MockFilmUsecaseMockRecorder) GetFilms(ctx, pager interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilms", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilms), ctx, pager)
}

// GetFilmsForCalendar mocks base method.
func (m *MockFilmUsecase) GetFilmsForCalendar(ctx context.Context, pager models.Pager, userID uuid.UUID) ([]models.FilmInCalendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsForCalendar", ctx, pager, userID)
	ret0, _ := ret[0].([]models.FilmInCalendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsForCalendar indicates an expected call of GetFilmsForCalendar.
func (mr *MockFilmUsecaseMockRecorder) GetFilmsForCalendar(ctx, pager, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsForCalendar", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilmsForCalendar), ctx, pager, userID)
}

// GetPromoFilm mocks base method.
func (m *MockFilmUsecase) GetPromoFilm(ctx context.Context) (models.PromoFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoFilm", ctx)
	ret0, _ := ret[0].(models.PromoFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoFilm indicates an expected call of GetPromoFilm.
func (mr *MockFilmUsecaseMockRecorder) GetPromoFilm(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoFilm", reflect.TypeOf((*MockFilmUsecase)(nil).GetPromoFilm), ctx)
}

// GetSimilarFilms mocks base method.
func (m *MockFilmUsecase) GetSimilarFilms(ctx context.Context, filmID uuid.UUID) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimilarFilms", ctx, filmID)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimilarFilms indicates an expected call of GetSimilarFilms.
func (mr *MockFilmUsecaseMockRecorder) GetSimilarFilms(ctx, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimilarFilms", reflect.TypeOf((*MockFilmUsecase)(nil).GetSimilarFilms), ctx, filmID)
}

// GetUsersFavFilms mocks base method.
func (m *MockFilmUsecase) GetUsersFavFilms(ctx context.Context, id uuid.UUID) ([]models.FavFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersFavFilms", ctx, id)
	ret0, _ := ret[0].([]models.FavFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersFavFilms indicates an expected call of GetUsersFavFilms.
func (mr *MockFilmUsecaseMockRecorder) GetUsersFavFilms(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersFavFilms", reflect.TypeOf((*MockFilmUsecase)(nil).GetUsersFavFilms), ctx, id)
}

// GetUsersRecommendations mocks base method.
func (m *MockFilmUsecase) GetUsersRecommendations(ctx context.Context, userID uuid.UUID) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersRecommendations", ctx, userID)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersRecommendations indicates an expected call of GetUsersRecommendations.
func (mr *MockFilmUsecaseMockRecorder) GetUsersRecommendations(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersRecommendations", reflect.TypeOf((*MockFilmUsecase)(nil).GetUsersRecommendations), ctx, userID)
}

// RemoveFilm mocks base method.
func (m *MockFilmUsecase) RemoveFilm(ctx context.Context, userID, filmID uuid.UUID) ([]models.FavFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFilm", ctx, userID, filmID)
	ret0, _ := ret[0].([]models.FavFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFilm indicates an expected call of RemoveFilm.
func (mr *MockFilmUsecaseMockRecorder) RemoveFilm(ctx, userID, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilm", reflect.TypeOf((*MockFilmUsecase)(nil).RemoveFilm), ctx, userID, filmID)
}

// SaveFilm mocks base method.
func (m *MockFilmUsecase) SaveFilm(ctx context.Context, userID, filmID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFilm", ctx, userID, filmID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFilm indicates an expected call of SaveFilm.
func (mr *MockFilmUsecaseMockRecorder) SaveFilm(ctx, userID, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFilm", reflect.TypeOf((*MockFilmUsecase)(nil).SaveFilm), ctx, userID, filmID)
}

// SendFeedback mocks base method.
func (m *MockFilmUsecase) SendFeedback(ctx context.Context, req models.FilmFeedbackInput, filmID, userID uuid.UUID) (models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFeedback", ctx, req, filmID, userID)
	ret0, _ := ret[0].(models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFeedback indicates an expected call of SendFeedback.
func (mr *MockFilmUsecaseMockRecorder) SendFeedback(ctx, req, filmID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFeedback", reflect.TypeOf((*MockFilmUsecase)(nil).SendFeedback), ctx, req, filmID, userID)
}

// SetRating mocks base method.
func (m *MockFilmUsecase) SetRating(ctx context.Context, req models.FilmFeedbackInput, filmID, userID uuid.UUID) (models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", ctx, req, filmID, userID)
	ret0, _ := ret[0].(models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRating indicates an expected call of SetRating.
func (mr *MockFilmUsecaseMockRecorder) SetRating(ctx, req, filmID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockFilmUsecase)(nil).SetRating), ctx, req, filmID, userID)
}

// SiteMap mocks base method.
func (m *MockFilmUsecase) SiteMap(ctx context.Context) (models.Urlset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SiteMap", ctx)
	ret0, _ := ret[0].(models.Urlset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SiteMap indicates an expected call of SiteMap.
func (mr *MockFilmUsecaseMockRecorder) SiteMap(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SiteMap", reflect.TypeOf((*MockFilmUsecase)(nil).SiteMap), ctx)
}

// ValidateAndGetUser mocks base method.
func (m *MockFilmUsecase) ValidateAndGetUser(ctx context.Context, token string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndGetUser", ctx, token)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndGetUser indicates an expected call of ValidateAndGetUser.
func (mr *MockFilmUsecaseMockRecorder) ValidateAndGetUser(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndGetUser", reflect.TypeOf((*MockFilmUsecase)(nil).ValidateAndGetUser), ctx, token)
}

// MockFilmRepo is a mock of FilmRepo interface.
type MockFilmRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFilmRepoMockRecorder
}

// MockFilmRepoMockRecorder is the mock recorder for MockFilmRepo.
type MockFilmRepoMockRecorder struct {
	mock *MockFilmRepo
}

// NewMockFilmRepo creates a new mock instance.
func NewMockFilmRepo(ctrl *gomock.Controller) *MockFilmRepo {
	mock := &MockFilmRepo{ctrl: ctrl}
	mock.recorder = &MockFilmRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmRepo) EXPECT() *MockFilmRepoMockRecorder {
	return m.recorder
}

// CheckUserFeedbackExists mocks base method.
func (m *MockFilmRepo) CheckUserFeedbackExists(ctx context.Context, userID, filmID uuid.UUID) (models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserFeedbackExists", ctx, userID, filmID)
	ret0, _ := ret[0].(models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserFeedbackExists indicates an expected call of CheckUserFeedbackExists.
func (mr *MockFilmRepoMockRecorder) CheckUserFeedbackExists(ctx, userID, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserFeedbackExists", reflect.TypeOf((*MockFilmRepo)(nil).CheckUserFeedbackExists), ctx, userID, filmID)
}

// CheckUserLikeExists mocks base method.
func (m *MockFilmRepo) CheckUserLikeExists(ctx context.Context, userID, filmID uuid.UUID) (models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserLikeExists", ctx, userID, filmID)
	ret0, _ := ret[0].(models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserLikeExists indicates an expected call of CheckUserLikeExists.
func (mr *MockFilmRepoMockRecorder) CheckUserLikeExists(ctx, userID, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserLikeExists", reflect.TypeOf((*MockFilmRepo)(nil).CheckUserLikeExists), ctx, userID, filmID)
}

// CreateFeedback mocks base method.
func (m *MockFilmRepo) CreateFeedback(ctx context.Context, feedback models.FilmFeedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeedback", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFeedback indicates an expected call of CreateFeedback.
func (mr *MockFilmRepoMockRecorder) CreateFeedback(ctx, feedback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeedback", reflect.TypeOf((*MockFilmRepo)(nil).CreateFeedback), ctx, feedback)
}

// GetFilmAvgRating mocks base method.
func (m *MockFilmRepo) GetFilmAvgRating(ctx context.Context, filmID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmAvgRating", ctx, filmID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmAvgRating indicates an expected call of GetFilmAvgRating.
func (mr *MockFilmRepoMockRecorder) GetFilmAvgRating(ctx, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmAvgRating", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmAvgRating), ctx, filmID)
}

// GetFilmByID mocks base method.
func (m *MockFilmRepo) GetFilmByID(ctx context.Context, id uuid.UUID) (models.Film, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmByID", ctx, id)
	ret0, _ := ret[0].(models.Film)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmByID indicates an expected call of GetFilmByID.
func (mr *MockFilmRepoMockRecorder) GetFilmByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmByID", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmByID), ctx, id)
}

// GetFilmFeedbacks mocks base method.
func (m *MockFilmRepo) GetFilmFeedbacks(ctx context.Context, filmID uuid.UUID, limit, offset int) ([]models.FilmFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmFeedbacks", ctx, filmID, limit, offset)
	ret0, _ := ret[0].([]models.FilmFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmFeedbacks indicates an expected call of GetFilmFeedbacks.
func (mr *MockFilmRepoMockRecorder) GetFilmFeedbacks(ctx, filmID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmFeedbacks", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmFeedbacks), ctx, filmID, limit, offset)
}

// GetFilmPage mocks base method.
func (m *MockFilmRepo) GetFilmPage(ctx context.Context, filmID uuid.UUID) (models.FilmPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmPage", ctx, filmID)
	ret0, _ := ret[0].(models.FilmPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmPage indicates an expected call of GetFilmPage.
func (mr *MockFilmRepoMockRecorder) GetFilmPage(ctx, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmPage", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmPage), ctx, filmID)
}

// GetFilmsForCalendar mocks base method.
func (m *MockFilmRepo) GetFilmsForCalendar(ctx context.Context, limit, offset int) ([]models.FilmInCalendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsForCalendar", ctx, limit, offset)
	ret0, _ := ret[0].([]models.FilmInCalendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsForCalendar indicates an expected call of GetFilmsForCalendar.
func (mr *MockFilmRepoMockRecorder) GetFilmsForCalendar(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsForCalendar", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmsForCalendar), ctx, limit, offset)
}

// GetFilmsWithCursorPagination mocks base method.
func (m *MockFilmRepo) GetFilmsWithCursorPagination(ctx context.Context, cursor time.Time, offset int) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsWithCursorPagination", ctx, cursor, offset)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsWithCursorPagination indicates an expected call of GetFilmsWithCursorPagination.
func (mr *MockFilmRepoMockRecorder) GetFilmsWithCursorPagination(ctx, cursor, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsWithCursorPagination", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmsWithCursorPagination), ctx, cursor, offset)
}

// GetFilmsWithPagination mocks base method.
func (m *MockFilmRepo) GetFilmsWithPagination(ctx context.Context, limit, offset int) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsWithPagination", ctx, limit, offset)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsWithPagination indicates an expected call of GetFilmsWithPagination.
func (mr *MockFilmRepoMockRecorder) GetFilmsWithPagination(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsWithPagination", reflect.TypeOf((*MockFilmRepo)(nil).GetFilmsWithPagination), ctx, limit, offset)
}

// GetGenreTitle mocks base method.
func (m *MockFilmRepo) GetGenreTitle(ctx context.Context, genreID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenreTitle", ctx, genreID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenreTitle indicates an expected call of GetGenreTitle.
func (mr *MockFilmRepoMockRecorder) GetGenreTitle(ctx, genreID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenreTitle", reflect.TypeOf((*MockFilmRepo)(nil).GetGenreTitle), ctx, genreID)
}

// GetPromoFilmByID mocks base method.
func (m *MockFilmRepo) GetPromoFilmByID(ctx context.Context, id uuid.UUID) (models.PromoFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoFilmByID", ctx, id)
	ret0, _ := ret[0].(models.PromoFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoFilmByID indicates an expected call of GetPromoFilmByID.
func (mr *MockFilmRepoMockRecorder) GetPromoFilmByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoFilmByID", reflect.TypeOf((*MockFilmRepo)(nil).GetPromoFilmByID), ctx, id)
}

// GetSimilarFilms mocks base method.
func (m *MockFilmRepo) GetSimilarFilms(ctx context.Context, filmID uuid.UUID) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimilarFilms", ctx, filmID)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimilarFilms indicates an expected call of GetSimilarFilms.
func (mr *MockFilmRepoMockRecorder) GetSimilarFilms(ctx, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimilarFilms", reflect.TypeOf((*MockFilmRepo)(nil).GetSimilarFilms), ctx, filmID)
}

// GetUpdates mocks base method.
func (m *MockFilmRepo) GetUpdates(ctx context.Context, userID uuid.UUID, offset time.Time) ([]models.News, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdates", ctx, userID, offset)
	ret0, _ := ret[0].([]models.News)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUpdates indicates an expected call of GetUpdates.
func (mr *MockFilmRepoMockRecorder) GetUpdates(ctx, userID, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdates", reflect.TypeOf((*MockFilmRepo)(nil).GetUpdates), ctx, userID, offset)
}

// GetUserByLogin mocks base method.
func (m *MockFilmRepo) GetUserByLogin(ctx context.Context, login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockFilmRepoMockRecorder) GetUserByLogin(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockFilmRepo)(nil).GetUserByLogin), ctx, login)
}

// GetUsersFavFilms mocks base method.
func (m *MockFilmRepo) GetUsersFavFilms(ctx context.Context, id uuid.UUID) ([]models.FavFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersFavFilms", ctx, id)
	ret0, _ := ret[0].([]models.FavFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersFavFilms indicates an expected call of GetUsersFavFilms.
func (mr *MockFilmRepoMockRecorder) GetUsersFavFilms(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersFavFilms", reflect.TypeOf((*MockFilmRepo)(nil).GetUsersFavFilms), ctx, id)
}

// GetUsersRecommendations mocks base method.
func (m *MockFilmRepo) GetUsersRecommendations(ctx context.Context, userID uuid.UUID) ([]models.RecFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersRecommendations", ctx, userID)
	ret0, _ := ret[0].([]models.RecFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersRecommendations indicates an expected call of GetUsersRecommendations.
func (mr *MockFilmRepoMockRecorder) GetUsersRecommendations(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersRecommendations", reflect.TypeOf((*MockFilmRepo)(nil).GetUsersRecommendations), ctx, userID)
}

// RemoveFilm mocks base method.
func (m *MockFilmRepo) RemoveFilm(ctx context.Context, userID, filmID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFilm", ctx, userID, filmID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFilm indicates an expected call of RemoveFilm.
func (mr *MockFilmRepoMockRecorder) RemoveFilm(ctx, userID, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilm", reflect.TypeOf((*MockFilmRepo)(nil).RemoveFilm), ctx, userID, filmID)
}

// SaveFilm mocks base method.
func (m *MockFilmRepo) SaveFilm(ctx context.Context, userID, filmID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFilm", ctx, userID, filmID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFilm indicates an expected call of SaveFilm.
func (mr *MockFilmRepoMockRecorder) SaveFilm(ctx, userID, filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFilm", reflect.TypeOf((*MockFilmRepo)(nil).SaveFilm), ctx, userID, filmID)
}

// SetRating mocks base method.
func (m *MockFilmRepo) SetRating(ctx context.Context, feedback models.FilmFeedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRating indicates an expected call of SetRating.
func (mr *MockFilmRepoMockRecorder) SetRating(ctx, feedback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockFilmRepo)(nil).SetRating), ctx, feedback)
}

// UpdateFeedback mocks base method.
func (m *MockFilmRepo) UpdateFeedback(ctx context.Context, feedback models.FilmFeedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeedback", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeedback indicates an expected call of UpdateFeedback.
func (mr *MockFilmRepoMockRecorder) UpdateFeedback(ctx, feedback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeedback", reflect.TypeOf((*MockFilmRepo)(nil).UpdateFeedback), ctx, feedback)
}
