// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/auth/delivery/grpc/gen/auth_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gen "kinopoisk/internal/pkg/auth/delivery/grpc/gen"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAuthClient is a mock of AuthClient interface.
type MockAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientMockRecorder
}

// MockAuthClientMockRecorder is the mock recorder for MockAuthClient.
type MockAuthClientMockRecorder struct {
	mock *MockAuthClient
}

// NewMockAuthClient creates a new mock instance.
func NewMockAuthClient(ctrl *gomock.Controller) *MockAuthClient {
	mock := &MockAuthClient{ctrl: ctrl}
	mock.recorder = &MockAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthClient) EXPECT() *MockAuthClientMockRecorder {
	return m.recorder
}

// ChangeAvatar mocks base method.
func (m *MockAuthClient) ChangeAvatar(ctx context.Context, in *gen.ChangeAvatarRequest, opts ...grpc.CallOption) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangeAvatar", varargs...)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeAvatar indicates an expected call of ChangeAvatar.
func (mr *MockAuthClientMockRecorder) ChangeAvatar(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeAvatar", reflect.TypeOf((*MockAuthClient)(nil).ChangeAvatar), varargs...)
}

// ChangePassword mocks base method.
func (m *MockAuthClient) ChangePassword(ctx context.Context, in *gen.ChangePasswordRequest, opts ...grpc.CallOption) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangePassword", varargs...)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthClientMockRecorder) ChangePassword(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthClient)(nil).ChangePassword), varargs...)
}

// Disable2Fa mocks base method.
func (m *MockAuthClient) Disable2Fa(ctx context.Context, in *gen.Disable2FaRequest, opts ...grpc.CallOption) (*gen.Disable2FaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Disable2Fa", varargs...)
	ret0, _ := ret[0].(*gen.Disable2FaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable2Fa indicates an expected call of Disable2Fa.
func (mr *MockAuthClientMockRecorder) Disable2Fa(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable2Fa", reflect.TypeOf((*MockAuthClient)(nil).Disable2Fa), varargs...)
}

// Enable2Fa mocks base method.
func (m *MockAuthClient) Enable2Fa(ctx context.Context, in *gen.Enable2FaRequest, opts ...grpc.CallOption) (*gen.Enable2FaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Enable2Fa", varargs...)
	ret0, _ := ret[0].(*gen.Enable2FaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enable2Fa indicates an expected call of Enable2Fa.
func (mr *MockAuthClientMockRecorder) Enable2Fa(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable2Fa", reflect.TypeOf((*MockAuthClient)(nil).Enable2Fa), varargs...)
}

// GetUser mocks base method.
func (m *MockAuthClient) GetUser(ctx context.Context, in *gen.GetUserRequest, opts ...grpc.CallOption) (*gen.UserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUser", varargs...)
	ret0, _ := ret[0].(*gen.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthClientMockRecorder) GetUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthClient)(nil).GetUser), varargs...)
}

// LogOutUser mocks base method.
func (m *MockAuthClient) LogOutUser(ctx context.Context, in *gen.LogOutUserRequest, opts ...grpc.CallOption) (*gen.LogOutUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogOutUser", varargs...)
	ret0, _ := ret[0].(*gen.LogOutUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogOutUser indicates an expected call of LogOutUser.
func (mr *MockAuthClientMockRecorder) LogOutUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogOutUser", reflect.TypeOf((*MockAuthClient)(nil).LogOutUser), varargs...)
}

// SignInUser mocks base method.
func (m *MockAuthClient) SignInUser(ctx context.Context, in *gen.SignInRequest, opts ...grpc.CallOption) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignInUser", varargs...)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignInUser indicates an expected call of SignInUser.
func (mr *MockAuthClientMockRecorder) SignInUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInUser", reflect.TypeOf((*MockAuthClient)(nil).SignInUser), varargs...)
}

// SignInUserVK mocks base method.
func (m *MockAuthClient) SignInUserVK(ctx context.Context, in *gen.SignupVKRequest, opts ...grpc.CallOption) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignInUserVK", varargs...)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignInUserVK indicates an expected call of SignInUserVK.
func (mr *MockAuthClientMockRecorder) SignInUserVK(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInUserVK", reflect.TypeOf((*MockAuthClient)(nil).SignInUserVK), varargs...)
}

// SignUpUserVK mocks base method.
func (m *MockAuthClient) SignUpUserVK(ctx context.Context, in *gen.SignupVKRequest, opts ...grpc.CallOption) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignUpUserVK", varargs...)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUpUserVK indicates an expected call of SignUpUserVK.
func (mr *MockAuthClientMockRecorder) SignUpUserVK(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUpUserVK", reflect.TypeOf((*MockAuthClient)(nil).SignUpUserVK), varargs...)
}

// SignupUser mocks base method.
func (m *MockAuthClient) SignupUser(ctx context.Context, in *gen.SignupRequest, opts ...grpc.CallOption) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignupUser", varargs...)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupUser indicates an expected call of SignupUser.
func (mr *MockAuthClientMockRecorder) SignupUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupUser", reflect.TypeOf((*MockAuthClient)(nil).SignupUser), varargs...)
}

// ValidateAndGetUser mocks base method.
func (m *MockAuthClient) ValidateAndGetUser(ctx context.Context, in *gen.ValidateAndGetUserRequest, opts ...grpc.CallOption) (*gen.UserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidateAndGetUser", varargs...)
	ret0, _ := ret[0].(*gen.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndGetUser indicates an expected call of ValidateAndGetUser.
func (mr *MockAuthClientMockRecorder) ValidateAndGetUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndGetUser", reflect.TypeOf((*MockAuthClient)(nil).ValidateAndGetUser), varargs...)
}

// MockAuthServer is a mock of AuthServer interface.
type MockAuthServer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServerMockRecorder
}

// MockAuthServerMockRecorder is the mock recorder for MockAuthServer.
type MockAuthServerMockRecorder struct {
	mock *MockAuthServer
}

// NewMockAuthServer creates a new mock instance.
func NewMockAuthServer(ctrl *gomock.Controller) *MockAuthServer {
	mock := &MockAuthServer{ctrl: ctrl}
	mock.recorder = &MockAuthServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServer) EXPECT() *MockAuthServerMockRecorder {
	return m.recorder
}

// ChangeAvatar mocks base method.
func (m *MockAuthServer) ChangeAvatar(arg0 context.Context, arg1 *gen.ChangeAvatarRequest) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeAvatar", arg0, arg1)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeAvatar indicates an expected call of ChangeAvatar.
func (mr *MockAuthServerMockRecorder) ChangeAvatar(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeAvatar", reflect.TypeOf((*MockAuthServer)(nil).ChangeAvatar), arg0, arg1)
}

// ChangePassword mocks base method.
func (m *MockAuthServer) ChangePassword(arg0 context.Context, arg1 *gen.ChangePasswordRequest) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", arg0, arg1)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthServerMockRecorder) ChangePassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthServer)(nil).ChangePassword), arg0, arg1)
}

// Disable2Fa mocks base method.
func (m *MockAuthServer) Disable2Fa(arg0 context.Context, arg1 *gen.Disable2FaRequest) (*gen.Disable2FaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable2Fa", arg0, arg1)
	ret0, _ := ret[0].(*gen.Disable2FaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable2Fa indicates an expected call of Disable2Fa.
func (mr *MockAuthServerMockRecorder) Disable2Fa(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable2Fa", reflect.TypeOf((*MockAuthServer)(nil).Disable2Fa), arg0, arg1)
}

// Enable2Fa mocks base method.
func (m *MockAuthServer) Enable2Fa(arg0 context.Context, arg1 *gen.Enable2FaRequest) (*gen.Enable2FaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable2Fa", arg0, arg1)
	ret0, _ := ret[0].(*gen.Enable2FaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enable2Fa indicates an expected call of Enable2Fa.
func (mr *MockAuthServerMockRecorder) Enable2Fa(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable2Fa", reflect.TypeOf((*MockAuthServer)(nil).Enable2Fa), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockAuthServer) GetUser(arg0 context.Context, arg1 *gen.GetUserRequest) (*gen.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*gen.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthServerMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthServer)(nil).GetUser), arg0, arg1)
}

// LogOutUser mocks base method.
func (m *MockAuthServer) LogOutUser(arg0 context.Context, arg1 *gen.LogOutUserRequest) (*gen.LogOutUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogOutUser", arg0, arg1)
	ret0, _ := ret[0].(*gen.LogOutUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogOutUser indicates an expected call of LogOutUser.
func (mr *MockAuthServerMockRecorder) LogOutUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogOutUser", reflect.TypeOf((*MockAuthServer)(nil).LogOutUser), arg0, arg1)
}

// SignInUser mocks base method.
func (m *MockAuthServer) SignInUser(arg0 context.Context, arg1 *gen.SignInRequest) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignInUser", arg0, arg1)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignInUser indicates an expected call of SignInUser.
func (mr *MockAuthServerMockRecorder) SignInUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInUser", reflect.TypeOf((*MockAuthServer)(nil).SignInUser), arg0, arg1)
}

// SignInUserVK mocks base method.
func (m *MockAuthServer) SignInUserVK(arg0 context.Context, arg1 *gen.SignupVKRequest) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignInUserVK", arg0, arg1)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignInUserVK indicates an expected call of SignInUserVK.
func (mr *MockAuthServerMockRecorder) SignInUserVK(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInUserVK", reflect.TypeOf((*MockAuthServer)(nil).SignInUserVK), arg0, arg1)
}

// SignUpUserVK mocks base method.
func (m *MockAuthServer) SignUpUserVK(arg0 context.Context, arg1 *gen.SignupVKRequest) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUpUserVK", arg0, arg1)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUpUserVK indicates an expected call of SignUpUserVK.
func (mr *MockAuthServerMockRecorder) SignUpUserVK(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUpUserVK", reflect.TypeOf((*MockAuthServer)(nil).SignUpUserVK), arg0, arg1)
}

// SignupUser mocks base method.
func (m *MockAuthServer) SignupUser(arg0 context.Context, arg1 *gen.SignupRequest) (*gen.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignupUser", arg0, arg1)
	ret0, _ := ret[0].(*gen.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupUser indicates an expected call of SignupUser.
func (mr *MockAuthServerMockRecorder) SignupUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupUser", reflect.TypeOf((*MockAuthServer)(nil).SignupUser), arg0, arg1)
}

// ValidateAndGetUser mocks base method.
func (m *MockAuthServer) ValidateAndGetUser(arg0 context.Context, arg1 *gen.ValidateAndGetUserRequest) (*gen.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndGetUser", arg0, arg1)
	ret0, _ := ret[0].(*gen.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndGetUser indicates an expected call of ValidateAndGetUser.
func (mr *MockAuthServerMockRecorder) ValidateAndGetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndGetUser", reflect.TypeOf((*MockAuthServer)(nil).ValidateAndGetUser), arg0, arg1)
}

// mustEmbedUnimplementedAuthServer mocks base method.
func (m *MockAuthServer) mustEmbedUnimplementedAuthServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthServer")
}

// mustEmbedUnimplementedAuthServer indicates an expected call of mustEmbedUnimplementedAuthServer.
func (mr *MockAuthServerMockRecorder) mustEmbedUnimplementedAuthServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthServer", reflect.TypeOf((*MockAuthServer)(nil).mustEmbedUnimplementedAuthServer))
}

// MockUnsafeAuthServer is a mock of UnsafeAuthServer interface.
type MockUnsafeAuthServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeAuthServerMockRecorder
}

// MockUnsafeAuthServerMockRecorder is the mock recorder for MockUnsafeAuthServer.
type MockUnsafeAuthServerMockRecorder struct {
	mock *MockUnsafeAuthServer
}

// NewMockUnsafeAuthServer creates a new mock instance.
func NewMockUnsafeAuthServer(ctrl *gomock.Controller) *MockUnsafeAuthServer {
	mock := &MockUnsafeAuthServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeAuthServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeAuthServer) EXPECT() *MockUnsafeAuthServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedAuthServer mocks base method.
func (m *MockUnsafeAuthServer) mustEmbedUnimplementedAuthServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthServer")
}

// mustEmbedUnimplementedAuthServer indicates an expected call of mustEmbedUnimplementedAuthServer.
func (mr *MockUnsafeAuthServerMockRecorder) mustEmbedUnimplementedAuthServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthServer", reflect.TypeOf((*MockUnsafeAuthServer)(nil).mustEmbedUnimplementedAuthServer))
}
