// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/auth/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/auth/interfaces.go -destination=internal/pkg/auth/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt"
	uuid "github.com/satori/go.uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthUsecase is a mock of AuthUsecase interface.
type MockAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseMockRecorder
	isgomock struct{}
}

// MockAuthUsecaseMockRecorder is the mock recorder for MockAuthUsecase.
type MockAuthUsecaseMockRecorder struct {
	mock *MockAuthUsecase
}

// NewMockAuthUsecase creates a new mock instance.
func NewMockAuthUsecase(ctrl *gomock.Controller) *MockAuthUsecase {
	mock := &MockAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecase) EXPECT() *MockAuthUsecaseMockRecorder {
	return m.recorder
}

// CheckAuth mocks base method.
func (m *MockAuthUsecase) CheckAuth(ctx context.Context) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuth", ctx)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAuth indicates an expected call of CheckAuth.
func (mr *MockAuthUsecaseMockRecorder) CheckAuth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuth", reflect.TypeOf((*MockAuthUsecase)(nil).CheckAuth), ctx)
}

// GenerateToken mocks base method.
func (m *MockAuthUsecase) GenerateToken(id uuid.UUID, login string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", id, login)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthUsecaseMockRecorder) GenerateToken(id, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuthUsecase)(nil).GenerateToken), id, login)
}

// LogOutUser mocks base method.
func (m *MockAuthUsecase) LogOutUser(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogOutUser", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogOutUser indicates an expected call of LogOutUser.
func (mr *MockAuthUsecaseMockRecorder) LogOutUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogOutUser", reflect.TypeOf((*MockAuthUsecase)(nil).LogOutUser), ctx)
}

// ParseToken mocks base method.
func (m *MockAuthUsecase) ParseToken(token string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", token)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockAuthUsecaseMockRecorder) ParseToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockAuthUsecase)(nil).ParseToken), token)
}

// SignInUser mocks base method.
func (m *MockAuthUsecase) SignInUser(ctx context.Context, req models.SignInInput) (models.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignInUser", ctx, req)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignInUser indicates an expected call of SignInUser.
func (mr *MockAuthUsecaseMockRecorder) SignInUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInUser", reflect.TypeOf((*MockAuthUsecase)(nil).SignInUser), ctx, req)
}

// SignUpUser mocks base method.
func (m *MockAuthUsecase) SignUpUser(ctx context.Context, req models.SignUpInput) (models.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUpUser", ctx, req)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignUpUser indicates an expected call of SignUpUser.
func (mr *MockAuthUsecaseMockRecorder) SignUpUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUpUser", reflect.TypeOf((*MockAuthUsecase)(nil).SignUpUser), ctx, req)
}

// ValidateAndGetUser mocks base method.
func (m *MockAuthUsecase) ValidateAndGetUser(ctx context.Context, token string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndGetUser", ctx, token)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndGetUser indicates an expected call of ValidateAndGetUser.
func (mr *MockAuthUsecaseMockRecorder) ValidateAndGetUser(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndGetUser", reflect.TypeOf((*MockAuthUsecase)(nil).ValidateAndGetUser), ctx, token)
}

// MockAuthRepo is a mock of AuthRepo interface.
type MockAuthRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepoMockRecorder
	isgomock struct{}
}

// MockAuthRepoMockRecorder is the mock recorder for MockAuthRepo.
type MockAuthRepoMockRecorder struct {
	mock *MockAuthRepo
}

// NewMockAuthRepo creates a new mock instance.
func NewMockAuthRepo(ctrl *gomock.Controller) *MockAuthRepo {
	mock := &MockAuthRepo{ctrl: ctrl}
	mock.recorder = &MockAuthRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepo) EXPECT() *MockAuthRepoMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockAuthRepo) CheckUserExists(ctx context.Context, login string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", ctx, login)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockAuthRepoMockRecorder) CheckUserExists(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockAuthRepo)(nil).CheckUserExists), ctx, login)
}

// CheckUserLogin mocks base method.
func (m *MockAuthRepo) CheckUserLogin(ctx context.Context, login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserLogin", ctx, login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserLogin indicates an expected call of CheckUserLogin.
func (mr *MockAuthRepoMockRecorder) CheckUserLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserLogin", reflect.TypeOf((*MockAuthRepo)(nil).CheckUserLogin), ctx, login)
}

// CreateUser mocks base method.
func (m *MockAuthRepo) CreateUser(ctx context.Context, user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthRepoMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthRepo)(nil).CreateUser), ctx, user)
}

// GetUserByLogin mocks base method.
func (m *MockAuthRepo) GetUserByLogin(ctx context.Context, login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockAuthRepoMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockAuthRepo)(nil).GetUserByLogin), ctx, login)
}

// IncrementUserVersion mocks base method.
func (m *MockAuthRepo) IncrementUserVersion(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUserVersion", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUserVersion indicates an expected call of IncrementUserVersion.
func (mr *MockAuthRepoMockRecorder) IncrementUserVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUserVersion", reflect.TypeOf((*MockAuthRepo)(nil).IncrementUserVersion), ctx, userID)
}
