// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/actors/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/satori/go.uuid"
)

// MockActorUsecase is a mock of ActorUsecase interface.
type MockActorUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockActorUsecaseMockRecorder
}

// MockActorUsecaseMockRecorder is the mock recorder for MockActorUsecase.
type MockActorUsecaseMockRecorder struct {
	mock *MockActorUsecase
}

// NewMockActorUsecase creates a new mock instance.
func NewMockActorUsecase(ctrl *gomock.Controller) *MockActorUsecase {
	mock := &MockActorUsecase{ctrl: ctrl}
	mock.recorder = &MockActorUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorUsecase) EXPECT() *MockActorUsecaseMockRecorder {
	return m.recorder
}

// GetActor mocks base method.
func (m *MockActorUsecase) GetActor(ctx context.Context, id uuid.UUID) (models.ActorPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActor", ctx, id)
	ret0, _ := ret[0].(models.ActorPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActor indicates an expected call of GetActor.
func (mr *MockActorUsecaseMockRecorder) GetActor(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActor", reflect.TypeOf((*MockActorUsecase)(nil).GetActor), ctx, id)
}

// GetFilmsByActor mocks base method.
func (m *MockActorUsecase) GetFilmsByActor(ctx context.Context, id uuid.UUID, pager models.Pager) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByActor", ctx, id, pager)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByActor indicates an expected call of GetFilmsByActor.
func (mr *MockActorUsecaseMockRecorder) GetFilmsByActor(ctx, id, pager interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByActor", reflect.TypeOf((*MockActorUsecase)(nil).GetFilmsByActor), ctx, id, pager)
}

// MockActorRepo is a mock of ActorRepo interface.
type MockActorRepo struct {
	ctrl     *gomock.Controller
	recorder *MockActorRepoMockRecorder
}

// MockActorRepoMockRecorder is the mock recorder for MockActorRepo.
type MockActorRepoMockRecorder struct {
	mock *MockActorRepo
}

// NewMockActorRepo creates a new mock instance.
func NewMockActorRepo(ctrl *gomock.Controller) *MockActorRepo {
	mock := &MockActorRepo{ctrl: ctrl}
	mock.recorder = &MockActorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorRepo) EXPECT() *MockActorRepoMockRecorder {
	return m.recorder
}

// GetActorByID mocks base method.
func (m *MockActorRepo) GetActorByID(ctx context.Context, id uuid.UUID) (models.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByID", ctx, id)
	ret0, _ := ret[0].(models.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockActorRepoMockRecorder) GetActorByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockActorRepo)(nil).GetActorByID), ctx, id)
}

// GetActorFilmsCount mocks base method.
func (m *MockActorRepo) GetActorFilmsCount(ctx context.Context, actorID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorFilmsCount", ctx, actorID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorFilmsCount indicates an expected call of GetActorFilmsCount.
func (mr *MockActorRepoMockRecorder) GetActorFilmsCount(ctx, actorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorFilmsCount", reflect.TypeOf((*MockActorRepo)(nil).GetActorFilmsCount), ctx, actorID)
}

// GetFilmsByActor mocks base method.
func (m *MockActorRepo) GetFilmsByActor(ctx context.Context, actorID uuid.UUID, limit, offset int) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByActor", ctx, actorID, limit, offset)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByActor indicates an expected call of GetFilmsByActor.
func (mr *MockActorRepoMockRecorder) GetFilmsByActor(ctx, actorID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByActor", reflect.TypeOf((*MockActorRepo)(nil).GetFilmsByActor), ctx, actorID, limit, offset)
}
