// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/genres/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/genres/interfaces.go -destination=internal/pkg/genres/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"

	uuid "github.com/satori/go.uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGenreUsecase is a mock of GenreUsecase interface.
type MockGenreUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGenreUsecaseMockRecorder
	isgomock struct{}
}

// MockGenreUsecaseMockRecorder is the mock recorder for MockGenreUsecase.
type MockGenreUsecaseMockRecorder struct {
	mock *MockGenreUsecase
}

// NewMockGenreUsecase creates a new mock instance.
func NewMockGenreUsecase(ctrl *gomock.Controller) *MockGenreUsecase {
	mock := &MockGenreUsecase{ctrl: ctrl}
	mock.recorder = &MockGenreUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenreUsecase) EXPECT() *MockGenreUsecaseMockRecorder {
	return m.recorder
}

// GetFilmsByGenre mocks base method.
func (m *MockGenreUsecase) GetFilmsByGenre(ctx context.Context, id uuid.UUID, pager models.Pager) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByGenre", ctx, id, pager)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByGenre indicates an expected call of GetFilmsByGenre.
func (mr *MockGenreUsecaseMockRecorder) GetFilmsByGenre(ctx, id, pager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByGenre", reflect.TypeOf((*MockGenreUsecase)(nil).GetFilmsByGenre), ctx, id, pager)
}

// GetGenre mocks base method.
func (m *MockGenreUsecase) GetGenre(ctx context.Context, id uuid.UUID) (models.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenre", ctx, id)
	ret0, _ := ret[0].(models.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenre indicates an expected call of GetGenre.
func (mr *MockGenreUsecaseMockRecorder) GetGenre(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenre", reflect.TypeOf((*MockGenreUsecase)(nil).GetGenre), ctx, id)
}

// GetGenres mocks base method.
func (m *MockGenreUsecase) GetGenres(ctx context.Context, pager models.Pager) ([]models.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenres", ctx, pager)
	ret0, _ := ret[0].([]models.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenres indicates an expected call of GetGenres.
func (mr *MockGenreUsecaseMockRecorder) GetGenres(ctx, pager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenres", reflect.TypeOf((*MockGenreUsecase)(nil).GetGenres), ctx, pager)
}

// MockGenreRepo is a mock of GenreRepo interface.
type MockGenreRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGenreRepoMockRecorder
	isgomock struct{}
}

// MockGenreRepoMockRecorder is the mock recorder for MockGenreRepo.
type MockGenreRepoMockRecorder struct {
	mock *MockGenreRepo
}

// NewMockGenreRepo creates a new mock instance.
func NewMockGenreRepo(ctrl *gomock.Controller) *MockGenreRepo {
	mock := &MockGenreRepo{ctrl: ctrl}
	mock.recorder = &MockGenreRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenreRepo) EXPECT() *MockGenreRepoMockRecorder {
	return m.recorder
}

// GetFilmsByGenre mocks base method.
func (m *MockGenreRepo) GetFilmsByGenre(ctx context.Context, genreID uuid.UUID, limit, offset int) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsByGenre", ctx, genreID, limit, offset)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsByGenre indicates an expected call of GetFilmsByGenre.
func (mr *MockGenreRepoMockRecorder) GetFilmsByGenre(ctx, genreID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsByGenre", reflect.TypeOf((*MockGenreRepo)(nil).GetFilmsByGenre), ctx, genreID, limit, offset)
}

// GetGenreByID mocks base method.
func (m *MockGenreRepo) GetGenreByID(ctx context.Context, id uuid.UUID) (models.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenreByID", ctx, id)
	ret0, _ := ret[0].(models.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenreByID indicates an expected call of GetGenreByID.
func (mr *MockGenreRepoMockRecorder) GetGenreByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenreByID", reflect.TypeOf((*MockGenreRepo)(nil).GetGenreByID), ctx, id)
}

// GetGenresWithPagination mocks base method.
func (m *MockGenreRepo) GetGenresWithPagination(ctx context.Context, count, offset int) ([]models.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenresWithPagination", ctx, count, offset)
	ret0, _ := ret[0].([]models.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenresWithPagination indicates an expected call of GetGenresWithPagination.
func (mr *MockGenreRepoMockRecorder) GetGenresWithPagination(ctx, count, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenresWithPagination", reflect.TypeOf((*MockGenreRepo)(nil).GetGenresWithPagination), ctx, count, offset)
}
