// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/search/delivery/grpc/gen/search_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gen "kinopoisk/internal/pkg/search/delivery/grpc/gen"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSearchClient is a mock of SearchClient interface.
type MockSearchClient struct {
	ctrl     *gomock.Controller
	recorder *MockSearchClientMockRecorder
}

// MockSearchClientMockRecorder is the mock recorder for MockSearchClient.
type MockSearchClientMockRecorder struct {
	mock *MockSearchClient
}

// NewMockSearchClient creates a new mock instance.
func NewMockSearchClient(ctrl *gomock.Controller) *MockSearchClient {
	mock := &MockSearchClient{ctrl: ctrl}
	mock.recorder = &MockSearchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchClient) EXPECT() *MockSearchClientMockRecorder {
	return m.recorder
}

// SearchFilmsAndActors mocks base method.
func (m *MockSearchClient) SearchFilmsAndActors(ctx context.Context, in *gen.SearchFilmsAndActorsRequest, opts ...grpc.CallOption) (*gen.SearchFilmsAndActorsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchFilmsAndActors", varargs...)
	ret0, _ := ret[0].(*gen.SearchFilmsAndActorsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFilmsAndActors indicates an expected call of SearchFilmsAndActors.
func (mr *MockSearchClientMockRecorder) SearchFilmsAndActors(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFilmsAndActors", reflect.TypeOf((*MockSearchClient)(nil).SearchFilmsAndActors), varargs...)
}

// MockSearchServer is a mock of SearchServer interface.
type MockSearchServer struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServerMockRecorder
}

// MockSearchServerMockRecorder is the mock recorder for MockSearchServer.
type MockSearchServerMockRecorder struct {
	mock *MockSearchServer
}

// NewMockSearchServer creates a new mock instance.
func NewMockSearchServer(ctrl *gomock.Controller) *MockSearchServer {
	mock := &MockSearchServer{ctrl: ctrl}
	mock.recorder = &MockSearchServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchServer) EXPECT() *MockSearchServerMockRecorder {
	return m.recorder
}

// SearchFilmsAndActors mocks base method.
func (m *MockSearchServer) SearchFilmsAndActors(arg0 context.Context, arg1 *gen.SearchFilmsAndActorsRequest) (*gen.SearchFilmsAndActorsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFilmsAndActors", arg0, arg1)
	ret0, _ := ret[0].(*gen.SearchFilmsAndActorsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFilmsAndActors indicates an expected call of SearchFilmsAndActors.
func (mr *MockSearchServerMockRecorder) SearchFilmsAndActors(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFilmsAndActors", reflect.TypeOf((*MockSearchServer)(nil).SearchFilmsAndActors), arg0, arg1)
}

// mustEmbedUnimplementedSearchServer mocks base method.
func (m *MockSearchServer) mustEmbedUnimplementedSearchServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSearchServer")
}

// mustEmbedUnimplementedSearchServer indicates an expected call of mustEmbedUnimplementedSearchServer.
func (mr *MockSearchServerMockRecorder) mustEmbedUnimplementedSearchServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSearchServer", reflect.TypeOf((*MockSearchServer)(nil).mustEmbedUnimplementedSearchServer))
}

// MockUnsafeSearchServer is a mock of UnsafeSearchServer interface.
type MockUnsafeSearchServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeSearchServerMockRecorder
}

// MockUnsafeSearchServerMockRecorder is the mock recorder for MockUnsafeSearchServer.
type MockUnsafeSearchServerMockRecorder struct {
	mock *MockUnsafeSearchServer
}

// NewMockUnsafeSearchServer creates a new mock instance.
func NewMockUnsafeSearchServer(ctrl *gomock.Controller) *MockUnsafeSearchServer {
	mock := &MockUnsafeSearchServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeSearchServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeSearchServer) EXPECT() *MockUnsafeSearchServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedSearchServer mocks base method.
func (m *MockUnsafeSearchServer) mustEmbedUnimplementedSearchServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSearchServer")
}

// mustEmbedUnimplementedSearchServer indicates an expected call of mustEmbedUnimplementedSearchServer.
func (mr *MockUnsafeSearchServerMockRecorder) mustEmbedUnimplementedSearchServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSearchServer", reflect.TypeOf((*MockUnsafeSearchServer)(nil).mustEmbedUnimplementedSearchServer))
}
