// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/search/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/search/interfaces.go -destination=internal/pkg/search/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kinopoisk/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchRepo is a mock of SearchRepo interface.
type MockSearchRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRepoMockRecorder
	isgomock struct{}
}

// MockSearchRepoMockRecorder is the mock recorder for MockSearchRepo.
type MockSearchRepoMockRecorder struct {
	mock *MockSearchRepo
}

// NewMockSearchRepo creates a new mock instance.
func NewMockSearchRepo(ctrl *gomock.Controller) *MockSearchRepo {
	mock := &MockSearchRepo{ctrl: ctrl}
	mock.recorder = &MockSearchRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRepo) EXPECT() *MockSearchRepoMockRecorder {
	return m.recorder
}

// GetActorsFromSearch mocks base method.
func (m *MockSearchRepo) GetActorsFromSearch(ctx context.Context, searchString string, limit, offset int) ([]models.MainPageActor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorsFromSearch", ctx, searchString, limit, offset)
	ret0, _ := ret[0].([]models.MainPageActor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorsFromSearch indicates an expected call of GetActorsFromSearch.
func (mr *MockSearchRepoMockRecorder) GetActorsFromSearch(ctx, searchString, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorsFromSearch", reflect.TypeOf((*MockSearchRepo)(nil).GetActorsFromSearch), ctx, searchString, limit, offset)
}

// GetFilmsFromSearch mocks base method.
func (m *MockSearchRepo) GetFilmsFromSearch(ctx context.Context, searchString string, limit, offset int) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsFromSearch", ctx, searchString, limit, offset)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsFromSearch indicates an expected call of GetFilmsFromSearch.
func (mr *MockSearchRepoMockRecorder) GetFilmsFromSearch(ctx, searchString, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsFromSearch", reflect.TypeOf((*MockSearchRepo)(nil).GetFilmsFromSearch), ctx, searchString, limit, offset)
}

// MockSearchUsecase is a mock of SearchUsecase interface.
type MockSearchUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSearchUsecaseMockRecorder
	isgomock struct{}
}

// MockSearchUsecaseMockRecorder is the mock recorder for MockSearchUsecase.
type MockSearchUsecaseMockRecorder struct {
	mock *MockSearchUsecase
}

// NewMockSearchUsecase creates a new mock instance.
func NewMockSearchUsecase(ctrl *gomock.Controller) *MockSearchUsecase {
	mock := &MockSearchUsecase{ctrl: ctrl}
	mock.recorder = &MockSearchUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchUsecase) EXPECT() *MockSearchUsecaseMockRecorder {
	return m.recorder
}

// GetActorsFromSearch mocks base method.
func (m *MockSearchUsecase) GetActorsFromSearch(ctx context.Context, searchString string, pager models.Pager) ([]models.MainPageActor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorsFromSearch", ctx, searchString, pager)
	ret0, _ := ret[0].([]models.MainPageActor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorsFromSearch indicates an expected call of GetActorsFromSearch.
func (mr *MockSearchUsecaseMockRecorder) GetActorsFromSearch(ctx, searchString, pager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorsFromSearch", reflect.TypeOf((*MockSearchUsecase)(nil).GetActorsFromSearch), ctx, searchString, pager)
}

// GetFilmsFromSearch mocks base method.
func (m *MockSearchUsecase) GetFilmsFromSearch(ctx context.Context, searchString string, pager models.Pager) ([]models.MainPageFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsFromSearch", ctx, searchString, pager)
	ret0, _ := ret[0].([]models.MainPageFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsFromSearch indicates an expected call of GetFilmsFromSearch.
func (mr *MockSearchUsecaseMockRecorder) GetFilmsFromSearch(ctx, searchString, pager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsFromSearch", reflect.TypeOf((*MockSearchUsecase)(nil).GetFilmsFromSearch), ctx, searchString, pager)
}
